document.addEventListener('DOMContentLoaded', () => {
    // Real Professor Data & Multi-language translations
    const translations = {
                ko: {
            site_title: "김미라 교수 - 원광대학교 한중관계연구원",
            site_description: "원광대학교 한중관계연구원 연구교수 김미라 교수의 공식 홈페이지입니다. 중국 고전산문, 문학비평, 한중비교문학 연구 및 주요 저서 정보를 제공합니다.",
            wku_name: "원광대학교",
            header_title: "한중관계연구원 연구교수",
            nav_profile: "프로필",
            nav_research: "연구분야",
            nav_publications: "학술성과",
            nav_contact: "연락처",
            hero_sub_title: "학문과 지혜의 조화",
            prof_name: "김미라",
            prof_title_suffix: "교수",
            hero_desc: "원광대학교 한중관계연구원에서 중국 고전산문을 연구하며, 전통의 깊이와 현대적 시각을 잇는 학문적 가교 역할을 수행하고 있습니다.",
            hero_btn_research: "연구 둘러보기",
            hero_btn_contact: "문의하기",
            prof_img_alt: "김미라 교수 프로필 사진",
            section_about_badge: "ABOUT",
            section_about_title: "학문적 여정",
            about_history_title: "학력 및 경력",
            about_history_1_date: "현재",
            about_history_1_desc: "원광대학교 한중관계연구원 연구교수",
            about_history_2_date: "최종학위",
            about_history_2_desc: "중국 복단대학(复旦大学) 문학 박사 (중국고대문학 전공)",
            about_content_p1: "중국 복단대학에서 중국고대문학 박사 학위를 취득한 후, 중국 고전 산문과 문학 비평, 그리고 한중 비교 문학 분야에서 심도 있는 연구를 수행하고 있습니다. 특히 고전 텍스트의 현대적 해석과 AI를 활용한 새로운 인문학적 접근에도 관심을 기울이고 있습니다.",
            about_quote: "\"학문은 과거와 현재를 잇는 대화이며, 사람과 시대를 이해하는 창입니다.\"",
            section_research_badge: "RESEARCH",
            section_research_title: "주요 연구 분야",
            research_1_title: "중국고전산문",
            research_1_desc: "당송팔대가를 비롯한 중국 고전 산문의 문체와 사상적 배경을 심도 있게 연구합니다.",
            research_2_title: "중국고전문학비평",
            research_2_desc: "고전 문학 이론과 비평사적 맥락을 통해 문학적 가치를 분석하고 재조명합니다.",
            research_3_title: "한중비교문학",
            research_3_desc: "한국과 중국 문학 간의 상호 영향과 교류 양상을 비교 문학적 관점에서 고찰합니다.",
            section_pub_badge: "PUBLICATIONS",
            section_pub_title: "학술 및 저술 활동",
            pub_tab_books: "저서",
            pub_tab_papers: "학술지 논문",
            pub_book_1_title: "『중국미술사2 (위진부터 수당까지)』",
            pub_book_1_info: "김미라, 홍기용 공역 | 다른생각 | 2011.",
            pub_paper_1_title: "「柳宗元의 『永州八記』의 認知的 解釋 初探—AI 이미지 생성과의 연계 시도를 겸하며」",
            pub_paper_1_info: "『中國散文硏究集刊』 18집, 2025.06.",
            pub_paper_2_title: "「왕우칭[王禹偁]의 율부 창작 시론」",
            pub_paper_2_info: "『한국인문융합연구』 제1집, 2024.12.",
            pub_paper_3_title: "「王禹偁의 『莊子』 제재 律賦 創作 小考」",
            pub_paper_3_info: "『열린정신 인문학 연구』 25집 제3호, 2024.12.",
            pub_paper_4_title: "「‘養花’와 ‘賞花’, 송대 도시 문인의 소확행 : 歐陽修의 ≪洛陽牡丹記≫를 중심으로」",
            pub_paper_4_info: "『中國散文硏究集刊』 15집, 2023.12.",
            pub_paper_5_title: "「배움과 기록의 전범화 고찰: 茅坤의 ≪唐宋八大家文鈔≫ 수록 ‘學記’를 중심으로」",
            pub_paper_5_info: "『中國散文硏究集刊』 13집, 2022.12.",
            contact_title: "CONTACT",
            contact_desc: "강연 의뢰, 학술 교류 및 기타 문의는 아래 연락처로 주시기 바랍니다.",
            contact_label_phone: "연락처",
            contact_label_email: "이메일",
            contact_label_office: "연구실",
            contact_office_value: "전라북도 익산시 익산대로 460 원광대학교 학군단 3층 한중관계연구원",
            contact_phone_value: "063-850-7120",
            form_placeholder_name: "성함",
            form_placeholder_email: "이메일",
            form_placeholder_message: "문의 내용을 입력해 주세요",
            form_submit: "보내기",
            form_success: "메시지가 성공적으로 전송되었습니다.",
            form_error: "오류가 발생했습니다. 잠시 후 다시 시도해 주세요.",
            footer_copyright: "© 2026 김미라 교수. All rights reserved.",
            wku_name_en: "WONKWANG UNIVERSITY",
            nav_mobile_toggle: "메뉴 토글",
            back_to_top_title: "위로 이동"
        },
                en: {
            site_title: "Professor Mira Kim - Wonkwang University",
            site_description: "Official website of Professor Mira Kim, Research Professor at the Institute for Korea-China Relations, Wonkwang University.",
            wku_name: "Wonkwang University",
            header_title: "Research Professor, Institute for Korea-China Relations",
            nav_profile: "Profile",
            nav_research: "Research",
            nav_publications: "Publications",
            nav_contact: "Contact",
            hero_sub_title: "Harmony of Wisdom & Academia",
            prof_name: "Mira Kim",
            prof_title_suffix: "Professor",
            hero_desc: "Researching classical Chinese literature at Wonkwang University, serving as an academic bridge between tradition and modern perspective.",
            hero_btn_research: "View Research",
            hero_btn_contact: "Contact Me",
            prof_img_alt: "Portrait of Professor Mira Kim",
            section_about_badge: "ABOUT",
            section_about_title: "Academic Journey",
            about_history_title: "Education & Career",
            about_history_1_date: "Present",
            about_history_1_desc: "Research Professor, Institute for Korea-China Relations, Wonkwang Univ.",
            about_history_2_date: "Degree",
            about_history_2_desc: "Ph.D. in Ancient Chinese Literature, Fudan University (China)",
            about_content_p1: "After obtaining a Ph.D. in Ancient Chinese Literature from Fudan University, I have been conducting in-depth research in classical Chinese prose, literary criticism, and comparative literature between Korea and China. I am particularly interested in modern interpretations of classical texts and new humanities approaches utilizing AI.",
            about_quote: "\"Scholarship is a conversation connecting the past and present, a window to understanding people and eras.\"",
            section_research_badge: "RESEARCH",
            section_research_title: "Key Research Areas",
            research_1_title: "Classical Chinese Prose",
            research_1_desc: "In-depth study of styles and ideological backgrounds of classical Chinese prose.",
            research_2_title: "Classical Literary Criticism",
            research_2_desc: "Analyzing literary values through classical theory and historical context.",
            research_3_title: "Comparative Literature",
            research_3_desc: "Examining interactions and exchanges between Korean and Chinese literature.",
            section_pub_badge: "PUBLICATIONS",
            section_pub_title: "Academic Activities",
            pub_tab_books: "Books",
            pub_tab_papers: "Journal Papers",
            pub_book_1_title: "History of Chinese Art 2 (Wei-Jin to Sui-Tang)",
            pub_book_1_info: "Co-translated by Mira Kim, Kiyong Hong | 2011.",
            pub_paper_1_title: "A Cognitive Interpretation of Liu Zongyuan's 'Eight Records of Yongzhou' — Including an Attempt to Link with AI Image Generation",
            pub_paper_1_info: "Journal of Chinese Prose, Vol. 18, 2025.06.",
            pub_paper_2_title: "Wang Yucheng's Poetic Theory of Lufu Creation",
            pub_paper_2_info: "Humanities Convergence Research, Vol. 1, 2024.12.",
            pub_paper_3_title: "A Study on Wang Yucheng's Lufu Creation Based on Zhuangzi",
            pub_paper_3_info: "Open Spirit Humanities Research, Vol. 25, No. 3, 2024.12.",
            pub_paper_4_title: "Flower Cultivation and Appreciation in Song Dynasty Urban Life",
            pub_paper_4_info: "Journal of Chinese Prose, Vol. 15, 2023.12.",
            pub_paper_5_title: "A Study on the Canonicalization of Learning and Records in Mao Kun",
            pub_paper_5_info: "Journal of Chinese Prose, Vol. 13, 2022.12.",
            contact_title: "CONTACT",
            contact_desc: "For lecture requests, academic exchange, or other inquiries, please contact me below.",
            contact_label_phone: "Phone",
            contact_label_email: "Email",
            contact_label_office: "Office",
            contact_office_value: "3F, Institute for Korea-China Relations, ROTC Building, Wonkwang University, 460 Iksan-daero, Iksan, Jeollabuk-do, Republic of Korea",
            contact_phone_value: "+82-63-850-7120",
            form_placeholder_name: "Name",
            form_placeholder_email: "Email",
            form_placeholder_message: "Enter your message",
            form_submit: "Send",
            form_success: "Message sent successfully.",
            form_error: "An error occurred. Please try again later.",
            footer_copyright: "© 2026 Professor Mira Kim. All rights reserved.",
            wku_name_en: "WONKWANG UNIVERSITY",
            nav_mobile_toggle: "Toggle Menu",
            back_to_top_title: "Back to Top"
        },
        zh: {
            site_title: "�𤑳�?? �蹱?- ���憭?郎�拐?�?頂�𠉛弦��",
            site_description: "���憭?郎�拐?�?頂�𠉛弦�� �𤑳�?? �蹱??䀹䲮?𤑳����蝏?�賢𧂈�豢袇�����??鸌霂���拐?瘥磰���?���?嗆��?�?,
            wku_name: "���憭?郎",
            header_title: "�拐?�?頂�𠉛弦�� �𠉛弦�蹱?,
            nav_profile: "?芯?蝞�隞?,
            nav_research: "�𠉛弦?�?,
            nav_publications: "???�?�",
            nav_contact: "�𠉛頂�??,
            hero_sub_title: "?????惣�抒��滚�",
            prof_name: "�𤑳�??",
            prof_title_suffix: "�蹱?,
            hero_desc: "�典��?之???銝?�?餌�蝛?堺?𦒘�?剖𤙴�文���郎�𠉛弦?諹稲�𥕢��?遣餈墧𦻖?删�瘛?漲?𡒊緵?��閫?�???獢交���",
            hero_btn_research: "�亦��??,
            hero_btn_contact: "�刻??行�",
            prof_img_alt: "�𤑳�?? �蹱??芯?�硋�",
            section_about_badge: "�喃?,
            section_about_title: "???���",
            about_history_title: "???��羓���",
            about_history_1_date: "�唬??,
            about_history_1_desc: "���憭?郎�拐?�?頂�𠉛弦�� �𠉛弦�蹱?,
            about_history_2_date: "��?�?雿?,
            about_history_2_desc: "?剖𤙴???????��?�𡁜??(?剖𤙴�支誨��郎)",
            about_content_p1: "�典��血之摮西繮?𦯀?�?隞��???�憯?郎?滚�嚗諹稲�??剖𤙴�文�������摮行鸌?���?葉?磰���郎��楛�??嗚��鸌�?�?典𧂈�豢��祉��唬誨霂𣳇�隞亙�?枏�AI��?���?嗆鰵頝?���",
            about_quote: '�?�?糓餈?餈�縧?𡒊緵�函�撖寡�?峕糓��圾??��?誨��������?,
            section_research_badge: "�𠉛弦",
            section_research_title: "?餉��??��",
            research_1_title: "?剖𤙴�文����",
            research_1_desc: "?勗��??�𡠺�𣂼��?之?嗅?���?剖𤙴�文�������雿?��脲��峕艶��",
            research_2_title: "?剖𤙴�文���郎�??,
            research_2_desc: "�朞��?���?��捏�峕鸌霂�蟮?剖�嚗���𣂼僎�齿鰵摰?���?隞?�??,
            research_3_title: "�拐?瘥磰���??,
            research_3_desc: "?擧�颲��??�閫??����?葉?文𤙴��?�渡��訾�敶?��𠹺漱?�?���?,
            section_pub_badge: "???瘣餃?,
            section_pub_title: "???�𡃏�餈?暑��",
            pub_tab_books: "�𦯀?,
            pub_tab_papers: "???霈箸�",
            pub_book_1_title: "�𠹺葉�賜��?蟮2?���贝秐�见�嚗?�?,
            pub_book_1_info: "�𤑳�??, ?芾絲�?��?| Dareun Saenggak | 2011.",
            pub_paper_1_title: "�峕𨺗?堒��𦠜?撌𧼮�霈?�讠�?斤䰻�??�𠰴��Ｔ�婙�𥪜�?箔�AI�曉�������蝏?�??�?,
            pub_paper_1_info: "�𠹺葉�賣袇���?園��𨳍�讠?8颲�, 2025.06.",
            pub_paper_2_title: "�𣬚�??�敺贝��??𡑒捏��",
            pub_paper_2_info: "�𢠃畆�賭?������蝛?�讠洵1颲�, 2024.12.",
            pub_paper_3_title: "�𣬚�??��?�摮?�?��𣂼�?见�雿𨅯����?,
            pub_paper_3_info: "�𠰴��𡒊移?硺?��郎�𠉛弦�讠?5颲𤑳洵3��, 2024.12.",
            pub_paper_4_title: "���隞��?��鈭箇��?�晦�苷��𡏭��???�?,
            pub_paper_4_info: "�𠹺葉�賣袇���?園��𨳍�讠?5颲�, 2023.12.",
            pub_paper_5_title: "�諹��?�?�摰见�????���𧢲𤣰敶𨰝�??售�肽����",
            pub_paper_5_info: "�𠹺葉�賣袇���?園��𨳍�讠?3颲�, 2022.12.",
            contact_title: "�𠉛頂�??,
            contact_desc: "?脫���蝥?��郎�臭漱瘚���嗡��?砭?諹窈�?�?乩��孵��𠉛頂��",
            contact_label_phone: "�菔?,
            contact_label_email: "�萄��桃拳",
            contact_label_office: "�??�",
            contact_office_value: "�函��?��𠰴控?��撅?之?�460 ���憭?郎�� ???��??� �拐?�?頂�𠉛弦��",
            contact_phone_value: "+82-63-850-7120",
            form_placeholder_name: "?枏?,
            form_placeholder_email: "�桃??,
            form_placeholder_message: "?瑁��亙�?�",
            form_submit: "�煾��",
            form_success: "?���?����麄��",
            form_error: "�𤑳��躰秤嚗諹窈?滚��滩���",
            footer_copyright: "?2026 �𤑳�?? �蹱��������?�?,
            wku_name_en: "WONKWANG UNIVERSITY",
            nav_mobile_toggle: "��??𨅯?,
            back_to_top_title: "餈𥪜�?園?
        },
        ja: {
            site_title: "�𤑳�?? �蹱?- ���憭?郎�⊿�銝?硄?��蝛?堺",
            site_description: "���憭?郎�⊿�銝?硄?��蝛?堺 �𤑳�?? �蹱?�砍��?��硔��?���?�?�?�����摮行鸌??���?剜�頛��??��???��垍?隞?��整��?,
            wku_name: "���憭?郎",
            header_title: "�㮖?�Ｖ��𠉛弦�� �𠉛弦�蹱?,
            nav_profile: "�?��?��潦?,
            nav_research: "�𠉛弦�睃?,
            nav_publications: "�𠉛弦?剔?",
            nav_contact: "�𠰴�����譌�",
            hero_sub_title: "???��?䰻�萸�隤踹�",
            prof_name: "�𤑳�??",
            prof_title_suffix: "�蹱?,
            hero_desc: "���憭?郎�⊿�銝?硄?��蝛?堺�找?�?�???��??𨰜���蝯?�?晞��?𣶹隞��?𣇉��垍��?郎?梶��?沲�烐��?��艾�敶孵𠧧�?��������踺��",
            hero_btn_research: "�𠉛弦�坿��?,
            hero_btn_contact: "�𠰴�����譌�",
            prof_img_alt: "�𤑳�?? �蹱?�腈�����潦?,
            section_about_badge: "ABOUT",
            section_about_title: "?????,
            about_history_title: "????喟??,
            about_history_1_date: "?銁",
            about_history_1_desc: "???⊿?剝硄靽?園????",
            about_history_2_date: "????,
            about_history_2_desc: "?剖𤙴 ?拇??????𡁜ㄚ (?剖𤙴????",
            about_content_p1: "?拇????批??噡???葉?豢袇摮行鸌??銝?頛???楛?嗚?䎚?整",
            about_quote: '?譌𤾸縧函𣶹?蝯?撖?店?𨳍犖?隞?踺麄桃??,
            section_research_badge: "RESEARCH",
            section_research_title: "?餉??,
            research_1_title: "?剖𤙴??,
            research_1_desc: "𣂼?之?嗚???剖𤙴?格?瓐?胯?晞???踺",
            research_2_title: "?剖𤙴?郎?,
            research_2_desc: "?郎?鸌?訫??行???∪??扳𨰜?,
            research_3_title: "㮖葉?磰??,
            research_3_desc: "?𤙴其?賬?瓐訾敶?其漱瘚?条㮾埝?摮衣芾嫘㕑𨰜?,
            section_pub_badge: "PUBLICATIONS",
            section_pub_title: "???𨳍?餈?暑",
            pub_tab_books: "??",
            pub_tab_papers: "??????,
            pub_book_1_title: "𦒘?賜?枏???卝?僐??,
            pub_book_1_info: "𤑳?? ?芾?? | Dareun Saenggak | 2011.",
            pub_paper_1_title: "峕𨺗摰?擧?撌𧼮??譌隤滨䰻?Ｕ",
            pub_paper_1_info: "𦒘?賣袇蝛??8, 2025.06.",
            pub_paper_2_title: "𣬚??桀???雿𡏭岫隢?,
            pub_paper_2_info: "𡡞??嗚讐洵1, 2024.12.",
            pub_paper_3_title: "𣬚???摮?誯𣂼???雿𨅯",
            pub_paper_3_info: "𡡞??移蟡硺犖?𠉛弦25?, 2024.12.",
            pub_paper_4_title: "?撣???晦踺䁅??",
            pub_paper_4_info: "𦒘?賣袇蝛??5, 2023.12.",
            pub_paper_5_title: "諹扎𤾸?见?????睃?閮覀?,
            pub_paper_5_info: "𦒘?賣袇蝛??3, 2022.12.",
            contact_title: "CONTACT",
            contact_desc: "?𥟇靘?聢?銵㮖漱?押?譌胯??窗扼?塩𨰜?,
            contact_label_phone: "餉店",
            contact_label_email: "E?,
            contact_label_office: "??",
            contact_office_value: "?烾??撣?勗之頝460 ???????3 㮖葉Ｖ𠉛弦",
            contact_phone_value: "+82-63-850-7120",
            form_placeholder_name: "?",
            form_placeholder_email: "E?,
            form_placeholder_message: "?鍦?艾𨬭",
            form_submit: "?,
            form_success: "～颯詻縑𨰻?麄",
            form_error: "?潦箇??批??𨰜譌??,
            footer_copyright: "?2026 𤑳??蹱ll rights reserved.",
            wku_name_en: "WONKWANG UNIVERSITY",
            nav_mobile_toggle: "～乓𤜯",
            back_to_top_title: "𨰜?
        },
        de: {
            site_title: "Prof. Mira Kim - Wonkwang Universität",
            site_description: "Offizielle Website von Professor Mira Kim, Forschungsprofessorin am Institut für Korea-China Beziehungen der Wonkwang Universität.",
            wku_name: "Wonkwang Universität",
            header_title: "Forschungsprofessorin, Institut für Korea-China Beziehungen",
            nav_profile: "Profil",
            nav_research: "Forschung",
            nav_publications: "Publikationen",
            nav_contact: "Kontakt",
            hero_sub_title: "Harmonie von Weisheit und Wissenschaft",
            prof_name: "Mira Kim",
            prof_title_suffix: "Professorin",
            hero_desc: "Erforschung der klassischen chinesischen Literatur an der Wonkwang Universität als akademische Brücke zwischen Tradition und Moderne.",
            hero_btn_research: "Forschung ansehen",
            hero_btn_contact: "Kontakt aufnehmen",
            prof_img_alt: "Porträt von Prof. Mira Kim",
            section_about_badge: "ÜBER MICH",
            section_about_title: "Akademischer Werdegang",
            about_history_title: "Bildung und Karriere",
            about_history_1_date: "Gegenwärtig",
            about_history_1_desc: "Forschungsprofessorin, Institut für Korea-China Beziehungen, Wonkwang Universität",
            about_history_2_date: "Abschluss",
            about_history_2_desc: "Promotion in klassischer chinesischer Literatur, Fudan Universität (China)",
            about_content_p1: "Nach meiner Promotion an der Fudan Universität forsche ich intensiv in den Bereichen klassische chinesische Prosa, Literaturkritik und vergleichende Literaturwissenschaft. Zudem interessiere ich mich für moderne Interpretationen klassischer Texte und neue Ansätze in den Geisteswissenschaften unter Einsatz von KI.",
            about_quote: '"Wissenschaft ist ein Dialog, der Vergangenheit und Gegenwart verbindet, und ein Fenster zum Verständnis von Menschen und Epochen."',
            section_research_badge: "FORSCHUNG",
            section_research_title: "Hauptforschungsgebiete",
            research_1_title: "Klassische chinesische Prosa",
            research_1_desc: "Untersuchung von Stil und ideologischem Hintergrund der klassischen chinesischen Prosa.",
            research_2_title: "Klassische Literaturkritik",
            research_2_desc: "Analyse literarischer Werte durch klassische Theorien und historische Kontexte.",
            research_3_title: "Vergleichende Literaturwissenschaft",
            research_3_desc: "Untersuchung der Wechselwirkungen zwischen koreanischer und chinesischer Literatur.",
            section_pub_badge: "PUBLIKATIONEN",
            section_pub_title: "Akademische Aktivitäten",
            pub_tab_books: "Bücher",
            pub_tab_papers: "Fachartikel",
            pub_book_1_title: "?Geschichte der chinesischen Kunst 2 (Von Wei-Jin bis Sui-Tang)??,
            pub_book_1_info: "Übersetzt von Mira Kim & Kiyong Hong | 2011.",
            pub_paper_1_title: "?Kognitive Interpretation von Liu Zongyuans 'Acht Aufzeichnungen von Yongzhou' ??Ein Versuch der Verbindung mit KI-Bildgenerierung??,
            pub_paper_1_info: "Journal of Chinese Prose, 2025.06.",
            pub_paper_2_title: "?Wang Yuchengs poetische Theorie der Lufu-Schöpfung??,
            pub_paper_2_info: "Humanities Convergence Research, 2024.12.",
            pub_paper_3_title: "?Studie über Wang Yuchengs Lufu-Schöpfung basierend auf Zhuangzi??,
            pub_paper_3_info: "Open Spirit Humanities Research, 2024.12.",
            pub_paper_4_title: "?Blumenzucht und -wertschätzung im städtischen Leben der Song-Dynastie??,
            pub_paper_4_info: "Journal of Chinese Prose, 2023.12.",
            pub_paper_5_title: "?Studie zur Kanonisierung des Lernens bei Mao Kun??,
            pub_paper_5_info: "Journal of Chinese Prose, 2022.12.",
            contact_title: "KONTAKT",
            contact_desc: "Für Anfragen zu Vorträgen, akademischem Austausch oder andere Anliegen kontaktieren Sie mich bitte wie folgt.",
            contact_label_phone: "Telefon",
            contact_label_email: "E-Mail",
            contact_label_office: "Büro",
            contact_office_value: "Etage 3, Institut für Korea-China Beziehungen, ROTC-Gebäude, Wonkwang Universität, 460 Iksan-daero, Iksan, Jeollabuk-do, Republik Korea",
            contact_phone_value: "+82-63-850-7120",
            form_placeholder_name: "Name",
            form_placeholder_email: "E-Mail",
            form_placeholder_message: "Ihre Nachricht",
            form_submit: "Senden",
            form_success: "Nachricht erfolgreich gesendet.",
            form_error: "Ein Fehler ist aufgetreten. Bitte versuchen Sie es später erneut.",
            footer_copyright: "© 2026 Prof. Mira Kim. Alle Rechte vorbehalten.",
            wku_name_en: "WONKWANG UNIVERSITY",
            nav_mobile_toggle: "Menü",
            back_to_top_title: "Nach oben"
        },
        es: {
            site_title: "Prof. Mira Kim - Universidad Wonkwang",
            site_description: "Sitio web oficial de la Prof. Mira Kim, profesora investigadora en el Instituto de Relaciones Corea-China de la Universidad Wonkwang.",
            wku_name: "Universidad Wonkwang",
            header_title: "Profesora Investigadora, Instituto de Relaciones Corea-China",
            nav_profile: "Perfil",
            nav_research: "Investigación",
            nav_publications: "Publicaciones",
            nav_contact: "Contacto",
            hero_sub_title: "Armonía de Sabiduría y Academia",
            prof_name: "Mira Kim",
            prof_title_suffix: "Profesora",
            hero_desc: "Investigadora de literatura clásica china en la Universidad Wonkwang, actuando como puente académico entre la tradición y la perspectiva moderna.",
            hero_btn_research: "Ver Investigación",
            hero_btn_contact: "Contactar",
            prof_img_alt: "Retrato de la Prof. Mira Kim",
            section_about_badge: "SOBRE MÍ",
            section_about_title: "Trayectoria Académica",
            about_history_title: "Educación y Carrera",
            about_history_1_date: "Actual",
            about_history_1_desc: "Profesora Investigadora, Instituto de Relaciones Corea-China, Universidad Wonkwang",
            about_history_2_date: "Título",
            about_history_2_desc: "Doctora en Literatura China Antigua, Universidad de Fudan (China)",
            about_content_p1: "Tras obtener mi doctorado en la Universidad de Fudan, realizo investigaciones profundas en prosa clásica china, crítica literaria y literatura comparada. También me interesan las interpretaciones modernas de textos clásicos y nuevos enfoques en humanidades usando IA.",
            about_quote: '"La academia es un diálogo que conecta el pasado y el presente, y una ventana para comprender a las personas y las épocas."',
            section_research_badge: "INVESTIGACIÓN",
            section_research_title: "Áreas Principales de Investigación",
            research_1_title: "Prosa Clásica China",
            research_1_desc: "Estudio del estilo y trasfondo ideológico de la prosa clásica china.",
            research_2_title: "Crítica Literaria Clásica",
            research_2_desc: "Análisis de valores literarios a través de teorías clásicas y contextos históricos.",
            research_3_title: "Literatura Comparada",
            research_3_desc: "Examen de las interacciones entre la literatura coreana y china.",
            section_pub_badge: "PUBLICACIONES",
            section_pub_title: "Actividades Académicas",
            pub_tab_books: "Libros",
            pub_paper_2_info: "Humanities Convergence Research, Vol. 1, 2024.12.",
            pub_paper_3_title: "Estudio sobre la creaci籀n de Lufu de Wang Yucheng basado en Zhuangzi",
            pub_paper_3_info: "Open Spirit Humanities Research, Vol. 25, No. 3, 2024.12.",
            pub_paper_4_title: "Cultivo y apreciaci籀n de flores en la vida urbana de la dinast穩a Song",
            pub_paper_4_info: "Journal of Chinese Prose, Vol. 15, 2023.12.",
            pub_paper_5_title: "Estudio sobre la canonizaci籀n del aprendizaje en Mao Kun",
            pub_paper_5_info: "Journal of Chinese Prose, Vol. 13, 2022.12.",
            contact_title: "CONTACTO",
            contact_desc: "Para solicitudes de conferencias, intercambio acad?mico u otras consultas, cont?cteme a continuaci籀n.",
            contact_label_phone: "Tel?fono",
            contact_label_email: "Correo",
            contact_label_office: "Oficina",
            contact_office_value: "Piso 3, Instituto de Relaciones Corea-China, Edificio ROTC, Universidad Wonkwang, 460 Iksan-daero, Iksan, Jeollabuk-do, Rep繳blica de Corea",
            contact_phone_value: "+82-63-850-7120",
            form_placeholder_name: "Nombre",
            form_placeholder_email: "Correo",
            form_placeholder_message: "Escriba su mensaje",
            form_submit: "Enviar",
            form_success: "Mensaje enviado con ?xito.",
            form_error: "Ocurri籀 un error. Int?ntelo de nuevo m?s tarde.",
            footer_copyright: "?2026 Prof. Mira Kim. Todos los derechos reservados.",
            wku_name_en: "WONKWANG UNIVERSITY",
            nav_mobile_toggle: "Men?,
            back_to_top_title: "Subir"
        },
        ne: {
            site_title: "?芹�鄐?冗?抉�鄐?冗?芹??桌?鄐?冗 ?𨫼凶?� - ?菽�鄐?�?温今鄐?� ?菽?鄐?�?菽今鄐賴丹?温仁鄐?仆?�",
            site_description: "?菽�鄐?�?温今鄐?� ?菽?鄐?�?菽今鄐賴丹?温仁鄐?仆?能�鄍??𨫼�?啤?鄐?冗-???� ?詮?温互?兒�鄐??�尹鄍�元?兒�鄐?冗?� ?詮�鄐??丞?鄐?亢?� ?芹�鄐?冗?抉�鄐?冗?芹??桌?鄐?冗 ?𨫼凶?桌�鄍??�之鄐賴�?擒什?賴??菽�鄐?元?擒�鄐颴奶",
            wku_name: "?菽�鄐?�?温今鄐?� ?菽?鄐?�?菽今鄐賴丹?温仁鄐?仆?�",
            header_title: "?�尹鄍�元?兒�鄐?冗?� ?芹�鄐?冗?抉�鄐?冗?芹? ?𨫼�?啤?鄐?冗-???� ?詮?温互?兒�鄐??�尹鄍�元?兒�鄐?冗?� ?詮�鄐??丞?鄐?,
            nav_profile: "?芹�鄐?�?徇?鄐�仆",
            nav_research: "?�尹鄍�元?兒�鄐?冗?�",
            nav_publications: "?芹�鄐?�?擒介鄐?允?啤?,
            nav_contact: "?詮?温云?啤�鄐?,
            hero_sub_title: "?厢�鄐??鄐??� ?眇�鄐?�?抉?鄐𨫼??詮丹鄍温五?擒?,
            prof_name: "?桌?鄐?冗 ?𨫼凶?�",
            prof_title_suffix: "?芹�鄐?冗?抉�鄐?冗?芹?,
            hero_desc: "?菽�鄐?�?温今鄐?� ?菽?鄐?�?菽今鄐賴丹?温仁鄐?仆?能?????兒?鄐?冗?� ?嗣?鄐??戈�鄐?�?� ?詮?鄐嫩凶?戈�鄐?�?� ?�尹鄍�元?兒�鄐?冗?� ?鉮什?温丹鄍? ?芹什?桌�鄐???� ?� ?�之鄍�尹?賴�鄐?冗 ?眇�鄐?�鄍??嗣�鄐𨫼�鄐?凶?� ?芹�鄐?�?� ?啤�鄐?亢?� ?詮�鄐?冗 ?鉮什?温丹鄍�奶",
            hero_btn_research: "?�尹鄍�元?兒�鄐?冗?� ?嫩�鄐?�?兒�鄐嫩�?詮?,
            hero_btn_contact: "?詮?温云?啤�鄐??鉮什?温尹鄍�允???鄍?,
            prof_img_alt: "?芹�鄐?冗?抉�鄐?冗?芹??桌?鄐?冗 ?𨫼凶?桌�鄍??徇�鄐颴�",
            section_about_badge: "?眇?鄐?�?桌??,
            section_about_title: "?嗣�鄐𨫼�鄐?凶?� ?能?鄐?�?啤??,
            about_history_title: "?嗣?鄐𨫼�鄐?冗 ?� ?𨫼??賴仁鄐?,
            about_history_1_date: "?嫩?鄐?,
            about_history_1_desc: "?�尹鄍�元?兒�鄐?冗?� ?芹�鄐?冗?抉�鄐?冗?芹? ?𨫼�?啤?鄐?冗-???� ?詮?温互?兒�鄐??�尹鄍�元?兒�鄐?冗?� ?詮�鄐??丞?鄐? ?菽�鄐?�?温今鄐?� ?菽?鄐?�?菽今鄐賴丹?温仁鄐?仆?�",
            about_history_2_date: "?﹤?鄐???啤?,
            about_history_2_desc: "???兒?鄐?冗?� ?芹�鄐?冗???� ?詮?鄐嫩凶?戈�鄐?亢?� ?菽?鄐?�?能?鄐?冗?啤?鄐?凶 (Ph.D.), ?徇�鄐?冗?� ?菽?鄐?�?菽今鄐賴丹?温仁鄐?仆?� (???�)",
            about_content_p1: "?徇�鄐?冗?� ?菽?鄐?�?菽今鄐賴丹?温仁鄐?仆?能互鄐?� ?芹�鄐?冗???� ???兒?鄐?冗?� ?詮?鄐嫩凶?戈�鄐?亢?� ?菽?鄐?�?能?鄐?冗?啤?鄐?凶 ?芹�鄐?冗?芹�鄐??鉮什?�云鄐𥔿?? ?� ???兒?鄐?冗?� ?嗣?鄐??戈�鄐?�?� ?鉮丹鄍温仁, ?詮?鄐嫩凶?戈�鄐?凶?� ?�仆鄍?�鄐?冗 ?� ?𨫼�?啤?鄐?冗 ?� ???� ?眇�鄐?�鄍??戈�鄐?尹?擒?温亢?� ?詮?鄐嫩凶?戈�鄐?亢?� ?𨫼�?兒�鄐?�?啤?鄐??鉮?鄐??�尹鄍�元?兒�鄐?冗?� ?鉮什?温丹鄍��?�??� ?菽?鄐?�?� ?鉮什?� ?嗣?鄐??戈�鄐?�?� ?芹?鄐?允?啤�鄐𨫼??�之鄍�尹?賴??菽�鄐?冗?遤�鄐?冗 ?� AI ?𨫼� ?芹�鄐?仁????鉮什?�什 ?兒仁鄐?� ?桌?鄐?今?賴�鄍??舟�鄐?�?颴?鄐𨫼�鄐?允?啤�鄐桌冗 ?啤�鄐????啤?鄐?�?𥔿�?�",
            about_quote: '"?𥔿冗?戈�鄐?今?�?温中?� ?菽?鄐?? ?� ?菽什?温?桌冗?兒仆鄐?� ?厢�鄐﹤�?兒??詮�鄐?冗?� ?嫩? ?� ?桌?鄐?凶?� ?� ?凼尹鄍�鄐嫩??��鄍??能�鄐??眇�鄐?�?兒??𥐰�?颴???瞹�鄐?冗?� ?嫩�鄍?奶?�"',
            section_research_badge: "?�尹鄍�元?兒�鄐?冗?�",
            section_research_title: "?芹�鄐?亢?�??�尹鄍�元?兒�鄐?冗?� ?𨫼�?獅�鄐?�?啤?鄐?�",
            research_1_title: "???兒?鄐?冗?� ?嗣?鄐??戈�鄐?�?� ?鉮丹鄍温仁",
            research_1_desc: "???兒?鄐?冗?� ?嗣?鄐??戈�鄐?�?� ?鉮丹鄍温仁?𨫼� ?嗣�鄐?� ?� ?菽?鄐??鄐?之?擒什?擒�鄍??鉮?鄐賴??� ?�之鄍温仁?能尹鄍?,
            research_2_title: "?嗣?鄐??戈�鄐?�?� ?詮?鄐嫩凶?戈�鄐?凶?� ?�仆鄍?�鄐?冗",
            research_2_desc: "?嗣?鄐??戈�鄐?�?� ?詮?鄐?�?抉?鄐?�?� ?� ?𩇫中?賴?鄐?元?賴??詮尹鄍温丹?啤�鄐??桌?鄐?�?徇??詮?鄐嫩凶?戈�鄐?凶?� ?桌�鄐?�?能?鄐?�?𨫼� ?菽?鄐?�?耜�?獅不鄍?,
            research_3_title: "?戈�鄐?尹?擒?温亢?� ?詮?鄐嫩凶?戈�鄐?,
            research_3_desc: "?𨫼�?啤?鄐?冗?耜� ?� ???兒?鄐?冗?� ?詮?鄐嫩凶?戈�鄐??眇�鄐?�鄍??�尹鄍温中?啤�鄍温??賴仁鄐?�?� ?芹什?�?𨫼�?獅不鄍?,
            section_pub_badge: "?芹�鄐?�?擒介鄐?允?啤?,
            section_pub_title: "?嗣�鄐𨫼�鄐?凶?� ?鉮?賴今?賴之鄐賴允?啤?,
            pub_tab_books: "?芹�鄐??戈�鄐嫩??�",
            pub_tab_papers: "?厢什?温尹鄐??芹�鄐???嫩什?�",
            pub_book_1_title: "???兒?鄐?冗?� ?𨫼仆?擒�鄍??�?賴允?擒???�",
            pub_book_1_info: "?桌?鄐?冗 ?𨫼凶?� ?� ?𨫼凶?能�鄐??嫩�鄐??舟�鄐?冗?啤???�尹鄍�今?擒丹鄐賴中 | ?兒它鄍?尼?�",
            pub_paper_1_title: "?耜凶?能??厢�鄐?�?鉮�鄐�尹?𨫼� '?能�鄐?�?厢�鄐𨫼???�??啤�鄐𨫼什?温丑鄐嫩??�' ?𨫼� ?詮�鄐???𠒎冗?兒?鄐?�?桌??菽�鄐?冗?遤�鄐?冗 �� AI ?𥔿今?� ?凼?温云?擒丹鄐?元?�??厢�鄐﹤�?兒??芹�鄐?仁?擒???詮?鄐賴中",
            pub_paper_1_info: "?厢什?温尹鄐??�????�尹鄐賴� ?鉮丹鄍温仁, ?遤不鄍温丑 ?抉? ?兒它鄍?市.?舟布鄍?,
            pub_paper_2_title: "?菽?鄐??能�鄐?�鄐跃�?� ?耜�?徇??詮?鄐?�?厢尹鄐?�?� ?𨫼冗?菽�鄐?凶?� ?詮?鄐?�?抉?鄐?�?�",
            pub_paper_2_info: "?嫩�鄐?�?桌�鄐?冗?兒?鄐颴�?� ?𨫼尹?温五鄐?�?厢�鄐?�?� ?啤?鄐???温? ?遤不鄍温丑 ?�, ?兒它鄍?左.?抉巨鄍?,
            pub_paper_3_title: "?瞹�鄐�尹?温�鄍�鄐桌冗 ?�之鄐???賴??菽?鄐??能�鄐?�鄐跃�?� ?耜�?徇??詮?鄐?�?厢尹鄐?亢?� �𦥑�?�鄐??�之鄍温仁?能?,
            pub_paper_3_info: "?㮙云鄐??詮�鄐?凶?啤?鄐??嫩�鄐?�?桌�鄐?冗?兒?鄐颴�?� ?啤?鄐???温? ?遤不鄍温丑 ?兒? ?��鄐??�, ?兒它鄍?左.?抉巨鄍?,
            pub_paper_4_title: "?詮�鄐??菽�鄐?�?� ?嗣?鄐?� ?厢�鄐?尹?桌???徇�鄐??遤�鄐?� ?� ?芹�鄐?介?�?鄐?,
            pub_paper_4_info: "?厢什?温尹鄐??�????�尹鄐賴� ?鉮丹鄍温仁, ?遤不鄍温丑 ?抉? ?兒它鄍?巧.?抉巨鄍?,
            pub_paper_5_title: "?桌?鄐??𨫼�?兒???詮?鄐𨫼?鄐??� ?啤�鄐𨫼什?温丑鄐𨫼??菽?鄐嫩凶?戈�鄐𨫼什?␡???𥐰� ?�之鄍温仁?能?,
            pub_paper_5_info: "?厢什?温尹鄐??�????�尹鄐賴� ?鉮丹鄍温仁, ?遤不鄍温丑 ?抉? ?兒它鄍?巨.?抉巨鄍?,
            contact_title: "?詮?温云?啤�鄐?,
            contact_desc: "?詮?温云?啤�鄐𨫼�鄍??耜冗?鉮???戈仆鄐𨫼??菽?鄐???� ?芹�鄐?仁????鉮什?温尹鄍�允???鄍温奶",
            contact_label_phone: "?徇�鄐?,
            contact_label_email: "?�?�仆",
            contact_label_office: "?𨫼冗?啤�鄐?冗?耜仁",
            contact_office_value: "?𨫼�?恷???�, ?𨫼�?啤?鄐?冗-???� ?詮?温互?兒�鄐??�尹鄍�元?兒�鄐?冗?� ?詮�鄐??丞?鄐? ROTC ?冢今鄐? ?菽�鄐?�?温今鄐?� ?菽?鄐?�?菽今鄐賴丹?温仁鄐?仆?�, ?芹布鄍??��鄍温元?擒??舟?鄐𥐰什?�, ?��鄍温元?擒? ?厢�鄐㮙仆?擒互鄍��-?﹤? ?𨫼�?啤?鄐?冗 ?鉮不鄐?尹?温?温?",
            contact_phone_value: "+?桌??眇??桌市鄍??冢尼鄍?它",
            form_placeholder_name: "?兒?鄐?,
            form_placeholder_email: "?�?�仆",
            form_placeholder_message: "?詮尹鄍温丹?�?,
            form_submit: "?芹�鄐?�?兒�鄐嫩�?詮?,
            form_success: "?詮尹鄍温丹?�??詮井鄐?中?擒云鄍�??温今鄐??芹�鄐?�?能�鄍?,
            form_error: "?戈�鄐?�?颴???冢仁鄍??,
            footer_copyright: "??兒它鄍?布 ?芹�鄐?冗?抉�鄐?冗?芹??桌?鄐?冗 ?𨫼凶?桌??詮互鄍??�之鄐賴�?擒什 ?詮�鄐?�?温仄鄐賴中?�",
            wku_name_en: "WONKWANG UNIVERSITY",
            nav_mobile_toggle: "諰𠰍尹?�",
            back_to_top_title: "?桌?鄐丞凶 ?厢?鄐?�?嫩�鄐?"
        },仁鄐?元 ?詮?鄐賴中",
            pub_paper_1_info: "?厢什?温尹鄐??�????�尹鄐賴� ?鉮丹鄍温仁, ?遤不鄍温丑 ?抉? ?兒它鄍?市.?舟布鄍?,
            pub_paper_2_title: "?菽?鄐??能�鄐?�鄐跃�?� ?耜�?徇??詮?鄐?�?厢尹鄐?�?� ?𨫼冗?菽�鄐?凶?� ?詮?鄐?�?抉?鄐?�?�",
            pub_paper_2_info: "?嫩�鄐?�?桌�鄐?冗?兒?鄐颴�?� ?𨫼尹?温五鄐?�?厢�鄐?�?� ?啤?鄐???温? ?遤不鄍温丑 ?�, ?兒它鄍?左.?抉巨鄍?,
            pub_paper_3_title: "?瞹�鄐�尹?温�鄍�鄐桌冗 ?�之鄐???賴??菽?鄐??能�鄐?�鄐跃�?� ?耜�?徇??詮?鄐?�?厢尹鄐?亢?� �𦥑�?�鄐??�之鄍温仁?能?,
            pub_paper_3_info: "?㮙云鄐??詮�鄐?凶?啤?鄐??嫩�鄐?�?桌�鄐?冗?兒?鄐颴�?� ?啤?鄐???温? ?遤不鄍温丑 ?兒? ?��鄐??�, ?兒它鄍?左.?抉巨鄍?,
            pub_paper_4_title: "?詮�鄐??菽�鄐?�?� ?嗣?鄐?� ?厢�鄐?尹?桌???徇�鄐??遤�鄐?� ?� ?芹�鄐?介?�?鄐?,
            pub_paper_4_info: "?厢什?温尹鄐??�????�尹鄐賴� ?鉮丹鄍温仁, ?遤不鄍温丑 ?抉? ?兒它鄍?巧.?抉巨鄍?,
            pub_paper_5_title: "?桌?鄐??𨫼�?兒???詮?鄐𨫼?鄐??� ?啤�鄐𨫼什?温丑鄐𨫼??菽?鄐嫩凶?戈�鄐𨫼什?␡???𥐰� ?�之鄍温仁?能?,
            pub_paper_5_info: "?厢什?温尹鄐??�????�尹鄐賴� ?鉮丹鄍温仁, ?遤不鄍温丑 ?抉? ?兒它鄍?巨.?抉巨鄍?,ok_1_info: "Co-traducido por Mira Kim, Kiyong Hong | Dareun Saenggak | 2011.",
            pub_paper_1_title: "Una interpretaci籀n cognitiva de los Ocho relatos de Yongzhou de Liu Zongyuan",
            pub_paper_1_info: "Journal of Chinese Prose, Vol. 18, 2025.06.",
            pub_paper_2_title: "La teor穩a po?tica de Wang Yucheng sobre la creaci籀n de Lufu",
            pub_paper_2_info: "Humanities Convergence Research, Vol. 1, 2024.12.",
            pub_paper_3_title: "Estudio sobre la creaci籀n de Lufu de Wang Yucheng basado en Zhuangzi",
            pub_paper_3_info: "Open Spirit Humanities Research, Vol. 25, No. 3, 2024.12.",
            pub_paper_4_title: "Cultivo y apreciaci籀n de flores en la vida urbana de la dinast穩a Song",
            pub_paper_4_info: "Journal of Chinese Prose, Vol. 15, 2023.12.",
            pub_paper_5_title: "Estudio sobre la canonizaci籀n del aprendizaje en Mao Kun",
            pub_paper_5_info: "Journal of Chinese Prose, Vol. 13, 2022.12.",
            contact_title: "CONTACTO",
            contact_desc: "Para solicitudes de conferencias, intercambio acad?mico u otras consultas, cont?cteme a continuaci籀n.",
            contact_label_phone: "Tel?fono",
            contact_label_email: "Correo",
            contact_label_office: "Oficina",
            contact_office_value: "Piso 3, Instituto de Relaciones Corea-China, Edificio ROTC, Universidad Wonkwang, 460 Iksan-daero, Iksan, Jeollabuk-do, Rep繳blica de Corea",
            contact_phone_value: "+82-63-850-7120",
            form_placeholder_name: "Nombre",
            form_placeholder_email: "Correo",
            form_placeholder_message: "Escriba su mensaje",
            form_submit: "Enviar",
            form_success: "Mensaje enviado con ?xito.",
            form_error: "Ocurri籀 un error. Int?ntelo de nuevo m?s tarde.",
            footer_copyright: "?2026 Prof. Mira Kim. Todos los derechos reservados.",
            wku_name_en: "WONKWANG UNIVERSITY",
            nav_mobile_toggle: "Men?,
            back_to_top_title: "Subir"
        },
        ne: {
            site_title: "?芹�鄐?冗?抉�鄐?冗?芹??桌?鄐?冗 ?𨫼凶?� - ?菽�鄐?�?温今鄐?� ?菽?鄐?�?菽今鄐賴丹?温仁鄐?仆?�",
            site_description: "?菽�鄐?�?温今鄐?� ?菽?鄐?�?菽今鄐賴丹?温仁鄐?仆?能�鄍??𨫼�?啤?鄐?冗-???� ?詮?温互?兒�鄐??�尹鄍�元?兒�鄐?冗?� ?詮�鄐??丞?鄐?亢?� ?芹�鄐?冗?抉�鄐?冗?芹??桌?鄐?冗 ?𨫼凶?桌�鄍??�之鄐賴�?擒什?賴??菽�鄐?元?擒�鄐颴奶",
            wku_name: "?菽�鄐?�?温今鄐?� ?菽?鄐?�?菽今鄐賴丹?温仁鄐?仆?�",
            header_title: "?�尹鄍�元?兒�鄐?冗?� ?芹�鄐?冗?抉�鄐?冗?芹? ?𨫼�?啤?鄐?冗-???� ?詮?温互?兒�鄐??�尹鄍�元?兒�鄐?冗?� ?詮�鄐??丞?鄐?,
            nav_profile: "?芹�鄐?�?徇?鄐�仆",
            nav_research: "?�尹鄍�元?兒�鄐?冗?�",
            nav_publications: "?芹�鄐?�?擒介鄐?允?啤?,
            nav_contact: "?詮?温云?啤�鄐?,
            hero_sub_title: "?厢�鄐??鄐??� ?眇�鄐?�?抉?鄐𨫼??詮丹鄍温五?擒?,
            prof_name: "?桌?鄐?冗 ?𨫼凶?�",
            prof_title_suffix: "?芹�鄐?冗?抉�鄐?冗?芹?,
            hero_desc: "?菽�鄐?�?温今鄐?� ?菽?鄐?�?菽今鄐賴丹?温仁鄐?仆?能?????兒?鄐?冗?� ?嗣?鄐??戈�鄐?�?� ?詮?鄐嫩凶?戈�鄐?�?� ?�尹鄍�元?兒�鄐?冗?� ?鉮什?温丹鄍? ?芹什?桌�鄐???� ?� ?�之鄍�尹?賴�鄐?冗 ?眇�鄐?�鄍??嗣�鄐𨫼�鄐?凶?� ?芹�鄐?�?� ?啤�鄐?亢?� ?詮�鄐?冗 ?鉮什?温丹鄍�奶",
            hero_btn_research: "?�尹鄍�元?兒�鄐?冗?� ?嫩�鄐?�?兒�鄐嫩�?詮?,
            hero_btn_contact: "?詮?温云?啤�鄐??鉮什?温尹鄍�允???鄍?,
            prof_img_alt: "?芹�鄐?冗?抉�鄐?冗?芹??桌?鄐?冗 ?𨫼凶?桌�鄍??徇�鄐颴�",
            section_about_badge: "?眇?鄐?�?桌??,
            section_about_title: "?嗣�鄐𨫼�鄐?凶?� ?能?鄐?�?啤??,
            about_history_title: "?嗣?鄐𨫼�鄐?冗 ?� ?𨫼??賴仁鄐?,
            about_history_1_date: "?嫩?鄐?,
            about_history_1_desc: "?�尹鄍�元?兒�鄐?冗?� ?芹�鄐?冗?抉�鄐?冗?芹? ?𨫼�?啤?鄐?冗-???� ?詮?温互?兒�鄐??�尹鄍�元?兒�鄐?冗?� ?詮�鄐??丞?鄐? ?菽�鄐?�?温今鄐?� ?菽?鄐?�?菽今鄐賴丹?温仁鄐?仆?�",
            about_history_2_date: "?﹤?鄐???啤?,
            about_history_2_desc: "???兒?鄐?冗?� ?芹�鄐?冗???� ?詮?鄐嫩凶?戈�鄐?亢?� ?菽?鄐?�?能?鄐?冗?啤?鄐?凶 (Ph.D.), ?徇�鄐?冗?� ?菽?鄐?�?菽今鄐賴丹?温仁鄐?仆?� (???�)",
            about_content_p1: "?徇�鄐?冗?� ?菽?鄐?�?菽今鄐賴丹?温仁鄐?仆?能互鄐?� ?菽?鄐?�?能?鄐?冗?啤?鄐?凶 ?芹�鄐?冗?芹�鄐??鉮什?�云鄐𥔿?? ?� ???兒?鄐?冗?� ?嗣?鄐??戈�鄐?�?� ?鉮丹鄍温仁, ?詮?鄐嫩凶?戈�鄐?凶?� ?�仆鄍?�鄐?冗 ?� ?戈�鄐?尹?擒?温亢?� ?詮?鄐嫩凶?戈�鄐?亢?� ?𨫼�?兒�鄐?�?啤?鄐??�尹鄍�元?兒�鄐?冗?� ?鉮什?温丹鄍��?�?,
            about_quote: '"?𥔿冗?戈�鄐?今?�?温中?� ?菽?鄐?? ?� ?菽什?温?桌冗?兒仆鄐?� ?厢�鄐﹤�?兒??詮�鄐?冗?� ?嫩�鄍?奶?�"',
            section_research_badge: "?�尹鄍�元?兒�鄐?冗?�",
            section_research_title: "?芹�鄐?亢?�??�尹鄍�元?兒�鄐?冗?� ?𨫼�?獅�鄐?�?啤?鄐?�",
            research_1_title: "???兒?鄐?冗?� ?嗣?鄐??戈�鄐?�?� ?鉮丹鄍温仁",
            research_1_desc: "???兒?鄐?冗?� ?嗣?鄐??戈�鄐?�?� ?鉮丹鄍温仁?𨫼� ?嗣�鄐?� ?� ?菽?鄐??鄐?之?擒什?擒�鄍??鉮?鄐賴??� ?�之鄍温仁?能尹鄍?,
            research_2_title: "?嗣?鄐??戈�鄐?�?� ?詮?鄐嫩凶?戈�鄐?凶?� ?�仆鄍?�鄐?冗",
            research_2_desc: "?嗣?鄐??戈�鄐?�?� ?詮?鄐?�?抉?鄐?�?� ?� ?𩇫中?賴?鄐?元?賴??詮尹鄍温丹?啤�鄐??桌?鄐?�?徇??詮?鄐嫩凶?戈�鄐?凶?� ?桌�鄐?�?能?鄐?�?𨫼� ?菽?鄐?�?耜�?獅不鄍?,
            research_3_title: "?戈�鄐?尹?擒?温亢?� ?詮?鄐嫩凶?戈�鄐?,
            research_3_desc: "?𨫼�?啤?鄐?冗?耜� ?� ???兒?鄐?冗?� ?詮?鄐嫩凶?戈�鄐??眇�鄐?�鄍??�尹鄍温中?啤�鄍温??賴仁鄐?�?� ?芹什?�?𨫼�?獅不鄍?,
            section_pub_badge: "?芹�鄐?�?擒介鄐?允?啤?,
            section_pub_title: "?嗣�鄐𨫼�鄐?凶?� ?鉮?賴今?賴之鄐賴允?啤?,
            pub_tab_books: "?芹�鄐??戈�鄐嫩??�",
            pub_tab_papers: "?厢什?温尹鄐??芹�鄐???嫩什?�",
            pub_book_1_title: "???兒?鄐?冗?� ?𨫼仆?擒�鄍??�?賴允?擒???�",
            pub_book_1_info: "?桌?鄐?冗 ?𨫼凶?� ?� ?𨫼凶?能�鄐??嫩�鄐??舟�鄐?冗?啤???�尹鄍�今?擒丹鄐賴中 | ?兒它鄍?尼?�",
            pub_paper_1_title: "?耜凶?能??厢�鄐?�?鉮�鄐�尹?𨫼� '?能�鄐?�?厢�鄐𨫼???�??啤�鄐𨫼什?温丑鄐嫩??�' ?𨫼� ?詮�鄐???𠒎冗?兒?鄐?�?桌??菽�鄐?冗?遤�鄐?冗",
            pub_paper_1_info: "?厢什?温尹鄐??�????�尹鄐賴� ?鉮丹鄍温仁, ?兒它鄍?市?�",
            contact_title: "?詮?温云?啤�鄐?,
            contact_desc: "?詮?温云?啤�鄐𨫼�鄍??耜冗?鉮???戈仆鄐𨫼??菽?鄐???� ?芹�鄐?仁????鉮什?温尹鄍�允???鄍温奶",
            contact_label_phone: "?徇�鄐?,
            contact_label_email: "?�?�仆",
            contact_label_office: "?𨫼冗?啤�鄐?冗?耜仁",
            contact_office_value: "?菽�鄐?�?温今鄐?� ?菽?鄐?�?菽今鄐賴丹?温仁鄐?仆?�, ?𨫼�?啤?鄐?冗",
            contact_phone_value: "?舟布鄍??桌市鄍??冢尼鄍?它",
            form_placeholder_name: "?兒?鄐?,
            form_placeholder_email: "?�?�仆",
            form_placeholder_message: "?詮尹鄍温丹?�?,
            form_submit: "?芹�鄐?�?兒�鄐嫩�?詮?,
            form_success: "?詮尹鄍温丹?�??詮井鄐?中?擒云鄍�??温今鄐??芹�鄐?�?能�鄍?,
            form_error: "?戈�鄐?�?颴???冢仁鄍??,
            footer_copyright: "??兒它鄍?布 ?芹�鄐?冗?抉�鄐?冗?芹??桌?鄐?冗 ?𨫼凶?桌?,
            wku_name_en: "WONKWANG UNIVERSITY",
            nav_mobile_toggle: "?桌�鄐?�",
            back_to_top_title: "?桌?鄐丞凶 ?厢?鄐?�?嫩�鄐?"
        },
        mn: {
            site_title: "��?�?�郋?�邽�訄 �邽??- �郋?郕赲訄?迣 �� ?��迣��?�",
            site_description: "�郋?郕赲訄?迣 �� ?��迣��?邽?郇 ?郋?郋?迣?�-??�訄迡�??�訄�邽?�訄訄?� ��迡�??�邽?迠?郅迣��郇?邿 �玼���郅�郇迣邽?郇 ?�?�?�郋?�邽�訄 �邽?邽?郇 訄郅訇訄??��?� 赲�訇�訄邿?",
            wku_name: "�郋?郕赲訄?迣 �� ?��迣��?�",
            header_title: "?郋?郋?迣?�-??�訄迡�??�訄�邽?�訄訄?� ��迡�??�邽?迠?郅迣��郇?邿 �玼���郅�郇迣邽?郇 ?�?�?�郋?,
            nav_profile: "��?�訄邿??,
            nav_research: "?�迡訄?迣訄訄",
            nav_publications: "衪�迡�??�邽?迠?郅迣��郇?邿 訇玼���郅",
            nav_contact: "???訇?郋 訇訄�邽?,
            hero_sub_title: "衪�迡�???�迡郅�迣 訇訄 ?��迣�郇 ��訄訄?� ?郋�邽�郋??,
            prof_name: "�邽�訄 �邽??,
            prof_title_suffix: "��?�?�郋?,
            hero_desc: "�郋?郕赲訄?迣 �� ?��迣��?�???�訄迡�??�郋?迣?迡?迣 ��訄郇 ?郋�邽?郅�郇 ��迡訄?迣訄訄 �邽?迠, �郅訄邾迠郅訄郅 訇訄 ?��邽???迮?邿??�郋?�?郇迡郋?��迡�??�邽?迠?郅迣��郇?邿 迣玼?� 訇郋?郋??訄迠?郅?訄?訇訄?郇?",
            hero_btn_research: "?�迡訄?迣訄訄 ?郱��",
            hero_btn_contact: "???訇?郋 訇訄�邽?,
            prof_img_alt: "��?�?�郋?�邽�訄 �邽?邽?郇 �茤�茤?,
            section_about_badge: "?苺???,
            section_about_title: "衪�迡邾?邿??訄�?訄??,
            about_history_title: "�郋?郋赲��郋??訇訄 ?訄��?",
            about_history_1_date: "�迡?郋",
            about_history_1_desc: "�郋?郕赲訄?迣 �� ?��迣��?邽?郇 ?郋?郋?迣?�-??�訄迡�??�訄�邽?�訄訄?� ��迡�??�邽?迠?郅迣��郇?邿 �玼���郅�郇迣邽?郇 ?�?�?�郋?,
            about_history_2_date: "����?,
            about_history_2_desc: "��????�郇 ?�迡訄?� �� ?��迣��?邽?郇 ?�訄郇 ?郋�邽?郅�郇 迡郋?�?� (??�訄迡�??���郇?邿 ��訄郇 ?郋�邽?郅)",
            about_content_p1: "?�迡訄?� �� ?��迣��?�???�訄迡�??���郇?邿 ��訄郇 ?郋�邽?郅�郇 �邽迣郅�郅��?迡郋?�?��郇 ?���?�訄?迣訄訄?�?� 迡訄�訄???�訄迡�??�郋?迣?迡?迣 ?�迣�?迠?郅��???迣, ��迣訄 ?郋�邽?郅�郇 �玼?邾? ?郋?郋?迣?�-??�訄迡�??�訄�����郅�訄??��訄郇 ?郋�邽?郅�郇 �邽迣郅�郅��?��迡訄?迣訄訄 �邽?迠 訇訄?郇? �茤??�郋?迣?迡?迣 訇邽�赲��?玼迡邽?郇 ?��邽???迮?邿??�訄?郅訇訄? �邽?邾�郅 ?��郇 ��訄訄?�?訄�?迣?訄�訄??�玼?玼?郇?�迣邽?郇 �邽?� �訄?迡?訄迣��迡�迣 �郋?邽��?郇 ��迡訄?迠 訇訄?郇?",
            about_quote: '"衪�迡�??�邽?迠?郅迣�?訇郋???郇迣茤��?郇 訇訄 ?迡?郋 ?迮?邿?�郋?訇?�?郇 ��?訄, �玼??訇訄 �訄??迮?邿??邿?迣?� �郋?� �邾."',
            section_research_badge: "?苺������",
            section_research_title: "?�迡訄?迣訄訄?� ?郇迡��郇 �邽迣郅�郅",
            research_1_title: "??�訄迡�??�郋?迣?迡?迣 ?�迣�?迠?郅��???迣",
            research_1_desc: "??�訄迡�??�郋?迣?迡?迣 ?�迣�?迠?郅��???迣?邽??��??訄�迣, ?郱�郅 ����?�??����?��迡訄?迣訄訄.",
            research_2_title: "?郋?迣?迡?迣 ��迣訄 ?郋�邽?郅�郇 �玼?邾?,
            research_2_desc: "?�迣訄 ?郋�邽?郅�郇 ?郇?��?邽?迣 ?郇?郅 訇郋?郋??�玼?��郇 ?茤��?郅 訇訄?迡訄郅??郇迡��郅�郇 �邽?迠?�?",
            research_3_title: "??�����郅�訄??��訄郇 ?郋�邽?郅",
            research_3_desc: "?郋?郋?迣?� 訇郋?郋????�訄迡�??��訄郇 ?郋�邽?郅�郇 �訄�邽?�訄郇 ?茤?茤?郅?邽?迣 ��迡郅訄�.",
            section_pub_badge: "�珖?衪衪�",
            section_pub_title: "衪�迡�??�邽?迠?郅迣��郇?邿 ?邿??訄迠?郅?訄迣訄?,
            pub_tab_books: "�郋??,
            pub_tab_papers: "衪�迡�??�邽?迠?郅迣��郇?邿 ?迣?玼?�??,
            pub_book_1_title: "�耨由𧤤�匾棋氵?��?訄迣邽?郇 �玼?� 2 (��??�邽?�-��??玼???訄??�玼���郅)��",
            pub_book_1_info: "�����郅�訄?? �邽�訄 �邽?? �邽�郇 ???迣 | 2011 ?郇.",
            pub_paper_1_title: "�芿軚� ��??�訄?�-?邿 '衩郇迠�迣邽?郇 ?訄?邾訄郇 ��?迡�迣?�??-?邿??�訄?邽???�迡��玼?郇 �訄?郅訇訄?�� ???邾�郅 ?��郇?迡玼��?�?��邿 �郋?訇?� ?�?郅迡郅?迣�郇 �訄?���",
            pub_paper_1_info: "??�訄迡�???�迣�?迠?郅��???迣 ��迡郅訄郅�郇 ���迣?玼?? 2025 ?郇.06.",
            pub_paper_2_title: "�芿??� 衩��郇?邿 ���� 訇玼���� ���� ?訄?�迣邽?郇 ?郇?郅��",
            pub_paper_2_info: "???玼?郇?�迣邽?郇 �訄?訇訄��郇 ��迡訄?迣訄訄, 2024.12.",
            pub_paper_3_title: "�芿??� 衩��郇?邿 '��訄郇?�' ��迡�赲� ���� 訇玼���� ���訄??��迡訄?迣訄訄��",
            pub_paper_3_info: "���郅���邿 ?��郇 �訄?訄?�玼?玼?郇?�迣邽?郇 ��迡訄?迣訄訄, 2024.12.",
            pub_paper_4_title: "�芿÷?� �郅��??�郋��??������?玼?迡?邿??'?���?�訄�邽? 訇訄 '?���?訇邽����' 訇訄�� 訇訄��迣訄?訄?? ���郇??邽�迣?邿??'�郋�郇?�郋迡訄??�邽' 迡��� ��?迣���郅訄郇��",
            pub_paper_4_info: "??�訄迡�???�迣�?迠?郅��???迣 ��迡郅訄郅�郇 ���迣?玼?? 2023.12.",
            pub_paper_5_title: "�芿×��?訇郋?郋赲��郋?訇訄 ��?迡�迣?�???郅迡��� ?邿??�赲��??訄迣赲訄��郅訄� ��迡訄?迣訄訄: �訄??��?� '?訄???玼??�訄 �訄 �� ��?� ?訄?? 迡訄�� '?�?�邽' 迡��� ��?迣���郅訄郇��",
            pub_paper_5_info: "??�訄迡�???�迣�?迠?郅��???迣 ��迡郅訄郅�郇 ���迣?玼?? 2022.12.",
            contact_title: "??���� ����??,
            contact_desc: "��?迣���郇迣玼???�迡��郅�郅 訄赲訄��迣 �玼�赲�郅 迡郋?�?�訄�迣訄訄?�郋?訇?迣迡郋?郋 ��.",
            contact_label_phone: "?�訄�",
            contact_label_email: "??�?郅",
            contact_label_office: "���邽?,
            contact_office_value: "�郋?郕赲訄?迣 �� ?��迣��?�, ��?苺",
            contact_phone_value: "063-850-7120",
            form_placeholder_name: "��?,
            form_placeholder_email: "??�?郅",
            form_placeholder_message: "���赲訄� 訇邽�邽?,
            form_submit: "�郅迣���",
            form_success: "���赲訄� 訄邾迠邽?��訄???郅迣��迣迡郅��.",
            form_error: "�郅迡訄?迣訄�郅訄訄.",
            footer_copyright: "?2026 ��?�?�郋?�邽�訄 �邽?? �玼?��?���郅?訄?�訄?迣訄訄?訄迣迡�訄??",
            wku_name_en: "WONKWANG UNIVERSITY",
            nav_mobile_toggle: "?�?,
            back_to_top_title: "������"
        },
        vi: {
            site_title: "Gi?o s??Mira Kim - �廕??h廙㷼 Wonkwang",
            site_description: "Trang web ch穩nh th廙妾 c廙吧 Gi?o s??Mira Kim, Gi?o s??Nghi礙n c廙? t廕?Vi廙?Quan h廙� H�n-Trung, �廕??h廙㷼 Wonkwang.",
            wku_name: "�廕??h廙㷼 Wonkwang",
            header_title: "Gi?o s??Nghi礙n c廙?, Vi廙?Quan h廙� H�n-Trung",
            nav_profile: "H廙� s??,
            nav_research: "Nghi礙n c廙?",
            nav_publications: "C繫ng tr穫nh khoa h廙㷼",
            nav_contact: "Li礙n h廙�",
            hero_sub_title: "S廙� h�i h簷a gi廙畝 Tr?tu廙� v?H廙㷼 thu廕負",
            prof_name: "Mira Kim",
            prof_title_suffix: "Gi?o s??,
            hero_desc: "Nghi礙n c廙? v�n h廙㷼 c廙� �i廙� Trung Qu廙?t廕?�廕??h廙㷼 Wonkwang, �?ng vai tr?l?c廕吟 n廙? h廙㷼 thu廕負 gi廙畝 truy廙� th廙𤉋g v?quan �i廙� hi廙?�廕??",
            hero_btn_research: "Xem Nghi礙n c廙?",
            hero_btn_contact: "Li礙n h廙�",
            prof_img_alt: "Ch?n dung Gi?o s??Mira Kim",
            section_about_badge: "GI廙䥑 THI廙�",
            section_about_title: "H�nh tr穫nh h廙㷼 thu廕負",
            about_history_title: "H廙㷼 v廕叩 & S廙� nghi廙㘥",
            about_history_1_date: "Hi廙?t廕?,
            about_history_1_desc: "Gi?o s??Nghi礙n c廙?, Vi廙?Quan h廙� H�n-Trung, �廕??h廙㷼 Wonkwang",
            about_history_2_date: "B廕彫g c廕叼",
            about_history_2_desc: "Ti廕積 s??V�n h廙㷼 Trung Qu廙?c廙� �廕?? �廕??h廙㷼 Ph廙卉 �獺n (Trung Qu廙?",
            about_content_p1: "Sau khi nh廕要 b廕彫g Ti廕積 s??v廙� V�n h廙㷼 Trung Qu廙?c廙� �廕??t廕?�廕??h廙㷼 Ph廙卉 �獺n, t繫i �瓊 th廙帷 hi廙?c?c nghi礙n c廙? s?u v廙� v�n xu繫i c廙� �i廙� Trung Qu廙? ph?b穫nh v�n h廙㷼 v?v�n h廙㷼 so s?nh H�n-Trung. T繫i c觼ng �廕??bi廙峼 quan t?m �廕?c?c di廙� gi廕?hi廙?�廕??v廙� v�n b廕?c廙� �i廙� v?c?c ph?①ng ph?p ti廕穆 c廕要 nh?n v�n m廙?s廙� d廙叩g AI.",
            about_quote: '"H廙㷼 thu廕負 l?cu廙緽 �廙魀 tho廕?k廕篙 n廙? qu??kh廙� v?hi廙?t廕? l?c廙苔 s廙� �廙?th廕只 hi廙� con ng?廙𩥉 v?th廙?�廕??"',
            section_research_badge: "NGHI�N C廙沃",
            section_research_title: "L?nh v廙帷 nghi礙n c廙? ch穩nh",
            research_1_title: "V�n xu繫i c廙� �i廙� Trung Qu廙?,
            research_1_desc: "Nghi礙n c廙? s?u v廙� phong c?ch v?b廙? c廕τh t??t?廙俲g c廙吧 v�n xu繫i c廙� �i廙� Trung Qu廙?",
            research_2_title: "Ph?b穫nh v�n h廙㷼 c廙� �i廙�",
            research_2_desc: "Ph?n t穩ch c?c gi??tr廙� v�n h廙㷼 th繫ng qua l?thuy廕篙 c廙� �i廙� v?b廙? c廕τh l廙醶h s廙�.",
            research_3_title: "V�n h廙㷼 so s?nh",
            research_3_desc: "Xem x?t s廙� t?①ng t?c v?giao l?u gi廙畝 v�n h廙㷼 H�n Qu廙?v?Trung Qu廙?",
            section_pub_badge: "C�NG B廙�",
            section_pub_title: "Ho廕? �廙㷌g h廙㷼 thu廕負",
            pub_tab_books: "S?ch",
            pub_tab_papers: "B�i b?o khoa h廙㷼",
            pub_book_1_title: "�穥廙醶h s廙� ngh廙� thu廕負 Trung Qu廙?2 (T廙� th廙?Ng廙句-T廕叩 �廕?T羅y-�⑹廙𩵚g)��",
            pub_book_1_info: "�廙忛g d廙醶h gi廕�: Mira Kim, Kiyong Hong | 2011.",
            pub_paper_1_title: "�㷉i廙� gi廕?nh廕要 th廙妾 v廙� 'V?nh Ch?u b?t k? c廙吧 Li廙� T繫ng Nguy礙n �� Bao g廙?n廙� l廙帷 k廕篙 n廙? v廙?t廕︽ 廕τh AI��",
            pub_paper_1_info: "T廕︾ ch?V�n xu繫i Trung Qu廙? T廕計 18, 2025.06.",
            pub_paper_2_title: "�𥴰羸 thuy廕篙 th??ca v廙� s?ng t?c Lu廕負 ph?c廙吧 V?①ng V?X廙姊g [Wang Yucheng]��",
            pub_paper_2_info: "Nghi礙n c廙? H廙?t廙� Nh?n v�n, T廕計 1, 2024.12.",
            pub_paper_3_title: "�𣊁i廙� kh廕?v廙� s?ng t?c Lu廕負 ph?d廙帶 tr礙n �廙?t�i 'Trang T廙�' c廙吧 V?①ng V?X廙姊g��",
            pub_paper_3_info: "Nghi礙n c廙? Nh?n v�n Tinh th廕吵 M廙�, T廕計 25, S廙� 3, 2024.12.",
            pub_paper_4_title: "��'D?廙?g hoa' v?'Th?廙俲g hoa', ni廙� h廕》h ph繳c nh廙� b??c廙吧 v�n nh?n �繫 th廙� th廙?T廙𤉋g: T廕計 trung v�o cu廙?'L廕︷ D?①ng M廕哎 �①n K? c廙吧 �u D?①ng Tu��",
            pub_paper_4_info: "T廕︾ ch?V�n xu繫i Trung Qu廙? T廕計 15, 2023.12.",
            pub_paper_5_title: "�𨨲ghi礙n c廙? v廙� s廙� �i廙� ph廕?h籀a c廙吧 vi廙?h廙㷼 v?ghi ch?p: T廕計 trung v�o ph廕吵 'H廙㷼 k? trong '�⑹廙𩵚g T廙𤉋g B?t �廕??Gia V�n Sao' c廙吧 Mao Kh繫n��",
            pub_paper_5_info: "T廕︾ ch?V�n xu繫i Trung Qu廙? T廕計 13, 2022.12.",
            contact_title: "LI�N H廙�",
            contact_desc: "Vui l簷ng li礙n h廙� v廙?t繫i qua th繫ng tin b礙n d?廙𢹂.",
            contact_label_phone: "�i廙?tho廕?,
            contact_label_email: "Email",
            contact_label_office: "V�n ph簷ng",
            contact_office_value: "�廕??h廙㷼 Wonkwang, H�n Qu廙?,
            contact_phone_value: "063-850-7120",
            form_placeholder_name: "H廙� t礙n",
            form_placeholder_email: "Email",
            form_placeholder_message: "N廙?dung tin nh廕疸",
            form_submit: "G廙虹",
            form_success: "Tin nh廕疸 �瓊 �⑹廙?g廙虹 th�nh c繫ng.",
            form_error: "�瓊 x廕ㄊ ra l廙?",
            footer_copyright: "?2026 Gi?o s??Mira Kim. B廕?l?u m廙幂 quy廙�.",
            wku_name_en: "WONKWANG UNIVERSITY",
            nav_mobile_toggle: "Menu",
            back_to_top_title: "V廙� �廕??trang"
        },
        bn: {
            site_title: "?�?鄑温旬?擒?鄏賴�?� ?桌江鄏?汙 ?𨫼江?� - ?㮙?鄏𨫼�鄏?汝?擒??眇江鄏?�?眇?鄏賴戌?温?鄏?曳?能?,
            site_description: "?㮙?鄏𨫼�鄏?汝?擒??眇江鄏?�?眇?鄏賴戌?温?鄏?曳?能汝鄑�旭 ?𨫼�?啤江鄏?汝?�-???� ?詮?鄑温扛?啤�鄏??鉮?鄑�朵?␡??�?鄏??颴江鄏颴江?凼�鄑�旭 ?鉮?鄑�朵?␡??�?鄑温旬?擒?鄏賴�?� ?桌江鄏?汙 ?𨫼江?桌�鄏??�?鄏賴次?賴?鄏潼汙?� ?㮙?鄏潼�?眇次鄏?�?颴?,
            wku_name: "?㮙?鄏𨫼�鄏?汝?擒??眇江鄏?�?眇?鄏賴戌?温?鄏?曳?能?,
            header_title: "?鉮?鄑�朵?␡??�?鄑温旬?擒?鄏賴�?�, ?𨫼�?啤江鄏?汝?�-???� ?詮?鄑温扛?啤�鄏??鉮?鄑�朵?␡??�?鄏??颴江鄏颴江?凼?,
            nav_profile: "?芹�鄏?�?徇汙鄏�曳",
            nav_research: "?鉮?鄑�朵?␡?,
            nav_publications: "?芹�鄏?�?擒?鄏?汙",
            nav_contact: "?能�鄏???能�鄏?,
            hero_sub_title: "?芹�鄏?�?温�鄏??� ?嗣江鄏𨫼�鄏?汙?� ?詮?鄏?�?眇?鄏?,
            prof_name: "?桌江鄏?汙 ?𨫼江?�",
            prof_title_suffix: "?�?鄑温旬?擒?鄏賴�?�",
            hero_desc: "?㮙?鄏𨫼�鄏?汝?擒??眇江鄏?�?眇?鄏賴戌?温?鄏?曳?能汝鄑????兒??抉�鄏?�?芹?鄑??詮汙鄏嫩江?戈�鄏??兒江鄏?汝?� ?鉮?鄑�朵?␡??𨫼旭?𥔿江, ?能??𩇫忖?賴此鄑温旬 ?� ?�?鄑�成?賴??舟�鄏?�?颴江鄏???温�鄏賴旭 ?桌?鄑温旬?� ?𥐰�?颴??𥐰�?擒式鄑�旨?賴??詮�鄏?�?眇?鄑温戍?� ?嫩江鄏??眇??𨫼汙?� ?𨫼旭?�?,
            hero_btn_research: "?鉮?鄑�朵?␡??舟�鄏?�?�",
            hero_btn_contact: "?能�鄏???能�鄏??𨫼旭?�??,
            prof_img_alt: "?�?鄑温旬?擒?鄏賴�?� ?桌江鄏?汙 ?𨫼江?桌�鄏??𥔿收?�",
            section_about_badge: "?詮?鄑温扛?啤�鄏𨫼?,
            section_about_title: "?𥐰�?擒式鄑�旨?賴??能汙鄏?�?啤?,
            about_history_title: "?嗣江鄏𨫼�鄏?汙 ?� ?𨫼旭?温?鄏???眇??,
            about_history_1_date: "?眇??温忖?桌汙鄏?,
            about_history_1_desc: "?鉮?鄑�朵?␡??�?鄑温旬?擒?鄏賴�?�, ?𨫼�?啤江鄏?汝?�-???� ?詮?鄑温扛?啤�鄏??鉮?鄑�朵?␡??�?鄏??颴江鄏颴江?凼? ?㮙?鄏𨫼�鄏?汝?擒??眇江鄏?�?眇?鄏賴戌?温?鄏?曳?能?,
            about_history_2_date: "?﹤江鄏???啤?,
            about_history_2_desc: "???兒??芹�鄏?汙???� ?詮汙鄏嫩江?戈�鄏?� ?芹江鄏𥐰�鄏?式鄏? ?徇�鄏?汙?� ?眇江鄏?�?眇?鄏賴戌?温?鄏?曳?能?(???�)",
            about_content_p1: "?徇�鄏?汙?� ?眇江鄏?�?眇?鄏賴戌?温?鄏?曳?能??丞�鄏𨫼??芹�鄏?汙???� ???兒??詮汙鄏嫩江?戈�鄏?� ?芹江鄏𥐰�鄏?式鄏??𨫼旭?擒???芹?? ?�?鄏????兒??抉�鄏?�?芹?鄑??鉮?鄑温旬, ?詮汙鄏嫩江?戈�鄏??詮?鄏?曳??�鄏?汙 ?𥐰收?� ?𨫼�?啤江鄏?汝?� ?� ???兒�鄏??桌?鄑温旬?� ?戈�鄏?成?擒?鄑�曳?� ?詮汙鄏嫩江?戈�鄏??兒江鄏?汝?� ?兒江鄏?江?﹤??鉮?鄑�朵?␡??𨫼旭?𥔿江?� ?�?鄏??眇江鄏?�?� ?𨫼旭?� ?抉�鄏?�?芹?鄑??芹汙鄏?�?能�鄏??�?鄑�成?賴??眇�鄏?汙?遤�鄏?汙 ?𥐰收?� AI ?眇�鄏?收?嫩汙鄏??𨫼旭?� ?兒忖鄑�成 ?桌汙鄏?收?賴??舟�鄏?�?颴江鄏???温�鄏賴忖?� ?��鄑温旭?嫩�鄍?,
            about_quote: '"?嗣江鄏𨫼�鄏?汙 ?嫩?鄑??�忖鄑�鄏??� ?眇??温忖?桌汙鄏?�?� ?詮�鄏?�?鉮�鄏?旭?� ?詮�鄏?汙?芹奶鄍?奶"',
            section_research_badge: "?鉮?鄑�朵?␡?,
            section_research_title: "?芹�鄏?戍?擒???鉮?鄑�朵?␡汙鄏??𨫼�?獅�鄏?�?�",
            research_1_title: "???兒??抉�鄏?�?芹?鄑??鉮?鄑温旬",
            research_1_desc: "???兒??抉�鄏?�?芹?鄑??鉮?鄑温旬?�???嗣�鄏?� ?𥐰收?� ?�?鄏?�?嗣江鄏??芹�鄏???桌江鄏??鉮?鄑�鄏??�?鄑温旬?能汝鄏?奶",
            research_2_title: "?抉�鄏?�?芹?鄑??詮汙鄏嫩江?戈�鄏??詮?鄏?曳??�鄏?汙",
            research_2_desc: "?抉�鄏?�?芹?鄑??戈忖鄑温忖?温???𥐰收?� ?𩇫忖?賴此鄏?次?賴??芹�鄏?�?𨫼�?獅汙鄏?�?�???桌汙鄏?�?能?鄑??詮汙鄏嫩江?戈�鄏?江?� ?桌�鄏?�?能?鄑????眇江鄏?�?耜�?獅忙鄍?,
            research_3_title: "?戈�鄏?成?擒?鄑�曳?� ?詮汙鄏嫩江?戈�鄏?,
            research_3_desc: "?𨫼�?啤江鄏?汝?擒???𥐰收?� ???兒??詮汙鄏嫩江?戈�鄏?�?� ?桌?鄑温旬?� ?桌江鄏丞次?温�鄑温旭?賴?鄏潼汙 ?芹??�鄏𨫼�鄏?汙 ?𨫼旭?擒?,
            section_pub_badge: "?芹�鄏?�?擒?鄏?汙",
            section_pub_title: "?𥐰�?擒式鄑�旨?賴??𨫼汙?啤�鄏?�?温???,
            pub_tab_books: "?眇?,
            pub_tab_papers: "?厢汙鄏?�?兒汙鄏??芹�鄏?汙?�",
            pub_book_1_title: "???兒??嗣江鄏?�?芹�鄏??�忖鄏賴??擒??�",
            pub_book_1_info: "?�?鄑�收?擒???𨫼旭?��鄑�成: ?桌江鄏?汙 ?𨫼江?�, ?𨫼江?能汝鄏??嫩?| ?兒?鄑?壯?�",
            pub_paper_1_title: "?耜江?� ?厢�鄏��?能汝鄑�旬?潼汙鄏?�?� '?�?鄏潼�?瞹??𥐰旭 ?��鄏颴江 ?啤�鄏𨫼??温式'-?𥐰旭 ?厢�鄏?汙鄏?�?能??眇�鄏?汙?遤�鄏?汙 �� AI ?�?鄑�� ?厢�鄏?汙?啤�鄏?成?�???詮汙鄏丞� ?能�鄏𨫼�鄏??𨫼旭?擒???芹�鄏?�?�?鄑温�?� ?詮?,
            pub_paper_1_info: "???兒??鉮?鄑温旬?�???厢汙鄏?�?兒汙鄏? ?冢?鄏賴�?� ?抉? ?兒?鄑?妨.?舟妞鄍?,
            pub_paper_2_title: "?㮙?鄏潼汙?� ?��鄏?�鄏??𥐰旭 ?耜�?徇??詮�鄏?�?颴江鄏??𨫼汙?眇�鄏?江?� ?戈忖鄑温忖?温??,
            pub_paper_2_info: "?嫩江鄏?旨?温?鄏?成?賴�鄏賴� ?𨫼成?冢汙鄏?�?�?鄑温次 ?啤江鄏??啤�鄏? ?冢?鄏賴�?� ?�, ?兒?鄑?妒.?抉夾鄍?,
            pub_paper_3_title: "?瞹�鄏?汝?擒�鄏?江-?� ?凼?鄏??冢江鄏?�?戈??𨫼旭?� ?㮙?鄏潼汙?� ?��鄏?�鄏??𥐰旭 ?耜�?徇??詮�鄏?�?颴江鄏??凼?鄏??𥐰�?颴??�?鄑温旬?能汝鄏?,
            pub_paper_3_info: "?㮙?鄑�成 ?詮�鄏?江?啤江鄏??嫩江鄏?旨?温?鄏?成?賴�鄏賴� ?啤江鄏??啤�鄏? ?冢?鄏賴�?� ?兒? ?詮�鄏?�?能??�, ?兒?鄑?妒.?抉夾鄍?,
            pub_paper_4_title: "?詮??啤汙鄏?收?�?鄑�旭 ?嗣此鄏??厢�鄏?成?� ?徇�鄏????� ?𥐰收?� ?芹�鄏?朱?�次鄏?,
            pub_paper_4_info: "???兒??鉮?鄑温旬?�???厢汙鄏?�?兒汙鄏? ?冢?鄏賴�?� ?抉? ?兒?鄑?妝.?抉夾鄍?,
            pub_paper_5_title: "?桌汙鄏??𨫼�?�-?𥐰旭 ?嗣江鄏𨫼�鄏?汙 ?� ?啤�鄏𨫼??温式?�???𨫼�?能汙鄏?�?兒汙鄏��?�?鄏??兒江鄏?汝?� ?𥐰�?颴??�?鄑温旬?能汝鄏?,
            pub_paper_5_info: "???兒??鉮?鄑温旬?�???厢汙鄏?�?兒汙鄏? ?冢?鄏賴�?� ?抉? ?兒?鄑?夾.?抉夾鄍?,
            contact_title: "?能�鄏???能�鄏?,
            contact_desc: "?能�鄏???能�鄏???� ?厢?鄑温旬 ?兒江鄏?�鄏??眇江鄏?旭?� ?眇�鄏?收?嫩汙鄏??𨫼旭?�?鄍?,
            contact_label_phone: "?徇�鄏?,
            contact_label_email: "?�?鄑�曳",
            contact_label_office: "?�?鄏賴次",
            contact_office_value: "?㮙?鄏𨫼�鄏?汝?擒??眇江鄏?�?眇?鄏賴戌?温?鄏?曳?能? ?舟�鄑温朵?賴??𨫼�?啤江鄏?汝?�",
            contact_phone_value: "?舟妞鄑??桌妨鄑??冢??它",
            form_placeholder_name: "?兒汙鄏?,
            form_placeholder_email: "?�?鄑�曳",
            form_placeholder_message: "?眇汙鄏?�?戈??耜江?遤�鄏?,
            form_submit: "?芹汙鄏?汙?�",
            form_success: "?眇汙鄏?�?戈??詮?鄏?早?擒?鄑??芹汙鄏?汙?兒??嫩?鄏潼�?𥔿�?�",
            form_error: "?𥐰�?颴??戈�鄏?�?颴??熈�鄑��?�?,
            footer_copyright: "??兒?鄑?妞 ?�?鄑温旬?擒?鄏賴�?� ?桌江鄏?汙 ?𨫼江?桌??詮??温收?詮�鄏?忖?温???詮�鄏?�?温?鄏賴忖?�",
            wku_name_en: "WONKWANG UNIVERSITY",
            nav_mobile_toggle: "?桌�鄏?�",
            back_to_top_title: "?凼?鄏?� ?能汙鄏?
        },
        az: {
            site_title: "Professor Mira Kim - Vonkvang Universiteti",
            site_description: "Vonkvang Universitetinin Koreya-�in M羹nasib�tl�ri Ara�d覺rma 襤nstitutunun t�dqiqat?覺 professoru Mira Kimin r�smi vebsayt?",
            wku_name: "Vonkvang Universiteti",
            header_title: "T�dqiqat?覺 Professor, Koreya-�in M羹nasib�tl�ri Ara�d覺rma 襤nstitutu",
            nav_profile: "Profil",
            nav_research: "T�dqiqat",
            nav_publications: "N��rl�r",
            nav_contact: "�laq?,
            hero_sub_title: "Hikm�t v?Akademiyan覺n Harmoniyas?,
            prof_name: "Mira Kim",
            prof_title_suffix: "Professor",
            hero_desc: "Vonkvang Universitetind?�in klassik �d�biyyat覺n?t�dqiq edir, �n�n?v?m羹asir perspektiv aras覺nda akademik k繹rp?rolunu oynay覺r.",
            hero_btn_research: "T�dqiqatlara bax",
            hero_btn_contact: "�laq?saxla",
            prof_img_alt: "Professor Mira Kimin portreti",
            section_about_badge: "HAQQINDA",
            section_about_title: "Akademik Yol",
            about_history_title: "T�hsil v?Karyera",
            about_history_1_date: "Haz覺rda",
            about_history_1_desc: "T�dqiqat?覺 Professor, Koreya-�in M羹nasib�tl�ri Ara�d覺rma 襤nstitutu",
            about_history_2_date: "D�r�c?,
            about_history_2_desc: "�in Q�dim �d�biyyat?羹zr?F�ls�f?Doktoru (Ph.D.), Fudan Universiteti (�in)",
            about_content_p1: "Fudan Universitetind?�in q�dim �d�biyyat?羹zr?doktorluq d�r�c�si ald覺qdan sonra �in klassik n�sri, �d�bi t�nqid v?Koreya-�in m羹qayis�li �d�biyyat?sah�sind?d�rin t�dqiqatlar apar覺ram. H�m?inin klassik m�tnl�rin m羹asir t�fsiri v?s羹ni intellektd�n istifad?ed�r�k yeni humanitar yana�malarla maraqlan覺ram.",
            about_quote: '"Elm ke?mi?v?indini birl��dir�n bir dialoqdur, insanlar?v?d繹vrl�ri anlamaq 羹癟羹n bir p�nc�r�dir."',
            section_research_badge: "T�DQ襤QAT",
            section_research_title: "�sas T�dqiqat Sah�l�ri",
            research_1_title: "�in Klassik N�sri",
            research_1_desc: "�in klassik n�srinin 羹slublar?v?ideoloji m�n��yinin d�rin t�dqiqi.",
            research_2_title: "Klassik �d�bi T�nqid",
            research_2_desc: "Klassik n�z�riyy?v?tarixi kontekst vasit�sil?�d�bi d�y�rl�rin t�hlili.",
            research_3_title: "M羹qayis�li �d�biyyat",
            research_3_desc: "Koreya v?�in �d�biyyat?aras覺ndak?qar�覺l覺ql?t�sirl�rin ara�d覺r覺lmas?",
            section_pub_badge: "N��RL�R",
            section_pub_title: "Akademik F�aliyy�t",
            pub_tab_books: "Kitablar",
            pub_tab_papers: "M�qal�l�r",
            pub_book_1_title: "�𦍑𨮹n 襤nc�s�n�t Tarixi 2 (Vey-Cind�n Suy-Tanad�k)��",
            pub_book_1_info: "H�mt�rc羹m�癟il�r: Mira Kim, Kiyong Hong | 2011.",
            pub_paper_1_title: "�𥴰iu Zonqyuan覺n 'Yonqjunun S�kkiz Qeydi'nin koqnitiv t�fsiri �� S羹ni intellektl?t�svir yaratma c�hdi il?birlikd��?,
            pub_paper_1_info: "Journal of Chinese Prose, Cild 18, 2025.06.",
            pub_paper_2_title: "�𡦀ang Yucheng-in Lufu yarat覺c覺l覺�?haqq覺nda poetik n�z�riyy�si��",
            pub_paper_2_info: "Humanitar Konvergensiya Ara�d覺rmalar? Cild 1, 2024.12.",
            pub_paper_3_title: "�𡦀ang Yucheng-in 'Zhuangzi' m繹vzusunda Lufu yarat覺c覺l覺�?haqq覺nda q覺sa t�dqiqat��",
            pub_paper_3_info: "A?覺q Ruh Humanitar Ara�d覺rmalar, Cild 25, No 3, 2024.12.",
            pub_paper_4_title: "��'G羹l yeti�dirm? v?'G羹ld�n z繹vq alma', Song s羹lal�si ��h�r ziyal覺lar覺n覺n sevinci: Ouyang Xiu-nun 'Luoyang Mudan Ji' �s�ri m�rk�zind��?,
            pub_paper_4_info: "Journal of Chinese Prose, Cild 15, 2023.12.",
            pub_paper_5_title: "�䁱䮗r�nm?v?qeyd etm�nin kanonla�d覺r覺lmas?haqq覺nda t�dqiqat: Mao Kun-un 'Tangsong Badajia Wenchao' �s�rind�ki 'Xueji' m�rk�zind��?,
            pub_paper_5_info: "Journal of Chinese Prose, Cild 13, 2022.12.",
            contact_title: "�LAQ?,
            contact_desc: "�laq?羹癟羹n a�a�覺dak?m�lumatlardan istifad?edin.",
            contact_label_phone: "Telefon",
            contact_label_email: "E-po?t",
            contact_label_office: "Ofis",
            contact_office_value: "Vonkvang Universiteti, Koreya",
            contact_phone_value: "063-850-7120",
            form_placeholder_name: "Ad",
            form_placeholder_email: "E-po?t",
            form_placeholder_message: "Mesaj覺n覺z",
            form_submit: "G繹nd�r",
            form_success: "Mesaj u�urla g繹nd�rildi.",
            form_error: "X�ta ba?verdi.",
            footer_copyright: "?2026 Professor Mira Kim. B羹t羹n h羹quqlar qorunur.",
            wku_name_en: "WONKWANG UNIVERSITY",
            nav_mobile_toggle: "Menyu",
            back_to_top_title: "Yuxar?
        },
        uz: {
            site_title: "Professor Mira Kim - Vonkvang Universiteti",
            site_description: "Vonkvang Universitetining Koreya-Xitoy munosabatlari ilmiy-tadqiqot instituti professori Mira Kimning rasmiy vebsayti.",
            wku_name: "Vonkvang Universiteti",
            header_title: "Tadqiqotchi professor, Koreya-Xitoy munosabatlari ilmiy-tadqiqot instituti",
            nav_profile: "Profil",
            nav_research: "Tadqiqot",
            nav_publications: "Nashrlar",
            nav_contact: "Aloqa",
            hero_sub_title: "Hikmat va ilmfanning uyg'unligi",
            prof_name: "Mira Kim",
            prof_title_suffix: "Professor",
            hero_desc: "Vonkvang universitetida Xitoy klassik adabiyotini tadqiq etadi, an'ana va zamonaviy qarashlar o'rtasida ilmiy ko'prik vazifasini o'taydi.",
            hero_btn_research: "Tadqiqotlarni ko'rish",
            hero_btn_contact: "Bog'lanish",
            prof_img_alt: "Professor Mira Kim portreti",
            section_about_badge: "HAQIDA",
            section_about_title: "Akademik yo'l",
            about_history_title: "Ta'lim va karyera",
            about_history_1_date: "Hozirda",
            about_history_1_desc: "Tadqiqotchi professor, Koreya-Xitoy munosabatlari ilmiy-tadqiqot instituti",
            about_history_2_date: "Daraja",
            about_history_2_desc: "Xitoy qadimgi adabiyoti bo'yicha fan doktori (Ph.D.), Fudan universiteti (Xitoy)",
            about_content_p1: "Fudan universitetida Xitoy qadimgi adabiyoti bo'yicha doktorlik darajasini olganimdan so'ng, Xitoy klassik nasri, adabiy tanqid va Koreya-Xitoy qiyosiy adabiyoti sohasida chuqur tadqiqotlar olib bormoqdaman. Shuningdek, klassik matnlarning zamonaviy talqini va sun'iy intellekt yordamida yangi gumanitar yondashuvlarga qiziqaman.",
            about_quote: '"Ilm-fan o\'tmish va bugunni bog\'lovchi muloqot, inson va davrni tushunish uchun oynadir."',
            section_research_badge: "TADQIQOT",
            section_research_title: "Asosiy tadqiqot yo'nalishlari",
            research_1_title: "Xitoy klassik nasri",
            research_1_desc: "Xitoy klassik nasrining uslublari va mafkuraviy asoslarini chuqur o'rganish.",
            research_2_title: "Klassik adabiy tanqid",
            research_2_desc: "Klassik nazariya va tarixiy kontekst orqali adabiy qadriyatlarni tahlil qilish.",
            research_3_title: "Qiyosiy adabiyot",
            research_3_desc: "Koreya va Xitoy adabiyoti o'rtasidagi o'zaro ta'sir va almashinuvlarni o'rganish.",
            section_pub_badge: "NASHRLLAR",
            section_pub_title: "Akademik faoliyat",
            pub_tab_books: "Kitoblar",
            pub_tab_papers: "Maqolalar",
            pub_book_1_title: "�竪itoy san'ati tarixi 2 (Vey-Szindan Suy-Tangacha)��",
            pub_book_1_info: "Tarjimonlar: Mira Kim, Kiyong Hong | 2011.",
            pub_paper_1_title: "�𥴰iu Zongyuanning 'Yongjuning sakkiz qaydi' asarining kognitiv talqini �� sun'iy intellekt tasviri bilan bog'lashga urinish bilan��",
            pub_paper_1_info: "Journal of Chinese Prose, 18-jild, 2025.06.",
            pub_paper_2_title: "�㲋ang Yuchengning Lufu yaratish bo'yicha poetik nazariyasi��",
            pub_paper_2_info: "Gumanitar konvergentsiya tadqiqotlari, 1-jild, 2024.12.",
            pub_paper_3_title: "�㲋ang Yuchengning 'Zhuangzi' mavzusidagi Lufu yaratishi haqida qisqacha tadqiqot��",
            pub_paper_3_info: "Ochiq ruh gumanitar tadqiqotlar, 25-jild, 3-son, 2024.12.",
            pub_paper_4_title: "��'Gul yetishtirish' va 'Guldan zavqlanish', Sung sulolasi shahar ziyolilarining quvonchi: Ouyang Xiuning 'Luoyang Mudan Ji' asari misolida��",
            pub_paper_4_info: "Journal of Chinese Prose, 15-jild, 2023.12.",
            pub_paper_5_title: "�辧'rganish va yozib olishni kanonizatsiya qilish bo'yicha tadqiqot: Mao Kunning 'Tangsong Badajia Wenchao' asaridagi 'Xueji' misolida��",
            pub_paper_5_info: "Journal of Chinese Prose, 13-jild, 2022.12.",
            contact_title: "ALOQA",
            contact_desc: "Bog'lanish uchun quyidagi ma'lumotlardan foydalaning.",
            contact_label_phone: "Telefon",
            contact_label_email: "Elektron pochta",
            contact_label_office: "Ofis",
            contact_office_value: "Vonkvang universiteti, Koreya",
            contact_phone_value: "063-850-7120",
            form_placeholder_name: "Ism",
            form_placeholder_email: "Elektron pochta",
            form_placeholder_message: "Xabaringiz",
            form_submit: "Yuborish",
            form_success: "Xabar muvaffaqiyatli yuborildi.",
            form_error: "Xatolik yuz berdi.",
            footer_copyright: "?2026 Professor Mira Kim. Barcha huquqlar himoyalangan.",
            wku_name_en: "WONKWANG UNIVERSITY",
            nav_mobile_toggle: "Menyu",
            back_to_top_title: "Yuqoriga"
        },
        id: {
            site_title: "Profesor Mira Kim - Universitas Wonkwang",
            site_description: "Situs web resmi Profesor Mira Kim, Profesor Riset di Institut Hubungan Korea-Tiongkok, Universitas Wonkwang.",
            wku_name: "Universitas Wonkwang",
            header_title: "Profesor Riset, Institut Hubungan Korea-Tiongkok",
            nav_profile: "Profil",
            nav_research: "Penelitian",
            nav_publications: "Publikasi",
            nav_contact: "Kontak",
            hero_sub_title: "Harmoni Kebijaksanaan & Akademisi",
            prof_name: "Mira Kim",
            prof_title_suffix: "Profesor",
            hero_desc: "Meneliti sastra klasik Tiongkok di Universitas Wonkwang, berfungsi sebagai jembatan akademik antara tradisi dan perspektif modern.",
            hero_btn_research: "Lihat Penelitian",
            hero_btn_contact: "Hubungi",
            prof_img_alt: "Potret Profesor Mira Kim",
            section_about_badge: "TENTANG",
            section_about_title: "Perjalanan Akademik",
            about_history_title: "Pendidikan & Karir",
            about_history_1_date: "Sekarang",
            about_history_1_desc: "Profesor Riset, Institut Hubungan Korea-Tiongkok, Universitas Wonkwang",
            about_history_2_date: "Gelar",
            about_history_2_desc: "Doktor Sastra Tiongkok Kuno, Universitas Fudan (Tiongkok)",
            about_content_p1: "Setelah memperoleh gelar Doktor dari Universitas Fudan, saya telah melakukan penelitian mendalam dalam prosa klasik Tiongkok, kritik sastra, dan sastra perbandingan.",
            about_quote: '"Beasiswa adalah percakapan yang menghubungkan masa lalu dan masa kini."',
            section_research_badge: "PENELITIAN",
            section_research_title: "Bidang Penelitian Utama",
            research_1_title: "Prosa Klasik Tiongkok",
            research_1_desc: "Studi mendalam tentang gaya dan latar belakang ideologis prosa klasik Tiongkok.",
            research_2_title: "Kritik Sastra Klasik",
            research_2_desc: "Menganalisis nilai-nilai sastra melalui teori klasik dan konteks sejarah.",
            research_3_title: "Sastra Perbandingan",
            research_3_desc: "Memeriksa interaksi dan pertukaran antara sastra Korea dan Tiongkok.",
            section_pub_badge: "PUBLIKASI",
            section_pub_title: "Aktivitas Akademik",
            pub_tab_books: "Buku",
            pub_tab_papers: "Jurnal",
            pub_book_1_title: "Sejarah Seni Tiongkok 2",
            pub_book_1_info: "Penerjemah bersama: Mira Kim, Kiyong Hong | 2011.",
            pub_paper_1_title: "Interpretasi kognitif terhadap 'Delapan Catatan Yongzhou' karya Liu Zongyuan",
            pub_paper_1_info: "Journal of Chinese Prose, 2025.",
            contact_title: "KONTAK",
            contact_desc: "Silakan hubungi saya melalui informasi di bawah ini.",
            contact_label_phone: "Telepon",
            contact_label_email: "Email",
            contact_label_office: "Kantor",
            contact_office_value: "Universitas Wonkwang, Korea",
            contact_phone_value: "063-850-7120",
            form_placeholder_name: "Nama",
            form_placeholder_email: "Email",
            form_placeholder_message: "Pesan Anda",
            form_submit: "Kirim",
            form_success: "Pesan berhasil dikirim.",
            form_error: "Terjadi kesalahan.",
            footer_copyright: "?2026 Profesor Mira Kim. Hak cipta dilindungi undang-undang.",
            wku_name_en: "WONKWANG UNIVERSITY",
            nav_mobile_toggle: "Menu",
            back_to_top_title: "Kembali ke Atas"
        },
        zh_hant: {
            site_title: "�𤑳�?? �蹱?- �枏�憭?飛�㮖?�?��𠉛弦��",
            site_description: "�枏�憭?飛�㮖?�?��𠉛弦�� �𤑳�?? �蹱??䀹䲮?脩����?嫣?�见𧂈�?�����摮??訫��㮖葉?磰���飛���蝛?��栶��",
            wku_name: "�枏�憭?飛",
            header_title: "�㮖?�?��𠉛弦�� �𠉛弦�蹱?,
            nav_profile: "�衤?蝪?�",
            nav_research: "�𠉛弦�睃?,
            nav_publications: "??��?�",
            nav_contact: "�舐鼠�孵�",
            hero_sub_title: "??���惣�抒��滚�",
            prof_name: "�𤑳�??",
            prof_title_suffix: "�蹱?,
            hero_desc: "�典��?之??�銝?�?��蝛?堺?硺�銝?��文���飛�𠉛弦?諹稲�𥟇䲰�?遣��𦻖�喟絞瘛?漲��𣶹?��閫?�??�璈𧢲��?,
            hero_btn_research: "�亦��??,
            hero_btn_contact: "?株岷閰??",
            prof_img_alt: "�𤑳�?? �蹱?�衤?�硋�",
            section_about_badge: "�?䲰",
            section_about_title: "??�甇?�",
            about_history_title: "??風�羓�?�",
            about_history_1_date: "�曆??,
            about_history_1_desc: "�枏�憭?飛�㮖?�?��𠉛弦�� �𠉛弦�蹱?,
            about_history_2_date: "��??飛雿?,
            about_history_2_desc: "?剖�敺?𠲸憭?飛 ��飛�𡁜??(?剖��??��?",
            about_content_p1: "�典?�血之摮貊㬢?堒�憯?飛?滚�嚗諹稲�𥟇䲰?剖��?�������??鸌閰訫��㮖?瘥磰���飛��楛�亦�蝛?��鸌�仿�瘜?𧂈�?�祉��?誨?桅�隞亙�??�AI��?���?嗆鰵頝?���",
            about_quote: '��飛銵𤘪糓��𦻖�𤾸縧��𣶹�?�?滩店嚗峕糓��?鈭箄���誨���������',
            section_research_badge: "�𠉛弦",
            section_research_title: "?餉��???�",
            research_1_title: "?剖��?���?,
            research_1_desc: "?勗��??�𡠺�𣂼��?之?嗅?�?�?剖��?�������?𥪜��脲��峕艶��",
            research_2_title: "?剖��?���飛�寡�",
            research_2_desc: "�誯��?���飛����峕鸌閰訫蟮???���𣂷?�齿鰵?抵���飛�?�潦��",
            research_3_title: "�㮖?瘥磰���?,
            research_3_desc: "?墧�頛��??�閫??����㮖葉�拙���飛�� axis ��㮾鈭??�踹�鈭?�?���?,
            section_pub_badge: "??�瘣餃�",
            section_pub_title: "??��𡃏�餈?暑��",
            pub_tab_books: "�𦯀?,
            pub_tab_papers: "??�隢𡝗?,
            pub_book_1_title: "�𠹺葉�讠�銵?蟮2?���?秐�见�嚗?�?,
            pub_book_1_info: "�𤑳�??��?韏?鍂 ��??| Dareun Saenggak | 2011.",
            pub_paper_1_title: "��𨺗?堒��𦠜?撌𧼮�閮塩�讠�?滨䰻�??�见��Ｔ�婙�𥪜�隢𤥁�AI�硋�������蝯𣂼�閰?�?,
            pub_paper_1_info: "�𠹺葉�𧢲袇���蝛?��𨳍�讠洵18?荔?025.06.",
            pub_paper_2_title: "���蝳孵�?贝?�?�?抵��?,
            pub_paper_2_info: "�𢠃��衤?������蝛?�讠洵1?荔?024.12.",
            pub_paper_3_title: "���蝳孵��𡃏�??�钅��𣂼�鞈血?雿𨅯����?,
            pub_paper_3_info: "�𢠃��𡒊移?硺?��飛�𠉛弦�讠?5?舐?��?024.12.",
            pub_paper_4_title: "���隞��?��鈭箇��屸��?�滩��諹��?�溻�?,
            pub_paper_4_info: "�𠹺葉�𧢲袇���蝛?��𨳍�讠洵15?荔?023.12.",
            pub_paper_5_title: "����?�?�摰见�????���𧢲𤣰����飛??�滩����",
            pub_paper_5_info: "�𠹺葉�𧢲袇���蝛?��𨳍�讠洵13?荔?022.12.",
            contact_title: "�舐鼠�孵�",
            contact_desc: "?𥟇���?���飛銵㮖漱?���?�?株岷嚗諹��誯�隞乩��?��?鼠��",
            contact_label_phone: "�餉?,
            contact_label_email: "�餃��?拳",
            contact_label_office: "颲?�摰?,
            contact_office_value: "�函��?��𠰴控?��撅?之?�460 �枏�憭?飛�� ??��??� �㮖?�?��𠉛弦��",
            contact_phone_value: "+82-63-850-7120",
            form_placeholder_name: "?枏?,
            form_placeholder_email: "�萇??,
            form_placeholder_message: "???�亙�?�",
            form_submit: "�潮��",
            form_success: "?���?���麄��",
            form_error: "�潛��?炊?諹�蝔滚��滩岫�?,
            footer_copyright: "?2026 �𤑳�?? �蹱����?𦠜��剹��",
            wku_name_en: "WONKWANG UNIVERSITY",
            nav_mobile_toggle: "����𨅯?,
            back_to_top_title: "餈𥪜���?
        },
        kk: {
            site_title: "��?�?�郋?�邽�訄 �邽??- �郋?郕赲訄?迣 ?郇?赲?�邽�迮��",
            site_description: "�郋?郕赲訄?迣 ?郇?赲?�邽�迮�� �郋�迮??���訄??�訄��?訄��訄�?��?�?邽-?迮���迮??郇��?����郇�? ?�?�?�郋�� �邽�訄 �邽?郇�? �迮�邾??赲迮?�訄?�?",
            wku_name: "�郋?郕赲訄?迣 ?郇?赲?�邽�迮��",
            header_title: "�迮���迮��??�?�?�郋? �郋�迮??���訄??�訄��?訄��訄�?��?�?邽-?迮���迮??郇��?���?,
            nav_profile: "��?�?郅?,
            nav_research: "�迮���迮?,
            nav_publications: "�訄�邽�郅訄郇�邾迡訄?,
            nav_contact: "�訄?郅訄郇��",
            hero_sub_title: "�訄?訄?�??迮??��?�?郇�? ?邿?迮��?�",
            prof_name: "�邽�訄 �邽??,
            prof_title_suffix: "��?�?�郋?,
            hero_desc: "�郋?郕赲訄?迣 ?郇?赲?�邽�迮��?迡?���訄???郅訄��邽?訄?�?�迡??迮��???迮���迮?迡? 迡���?� ?迮???訄?訄?訄�邽 ?茤?�訄�訄� 訄�訄��郇迡訄�� 訄郕訄迡??�?�??茤?�?��?邾?�郇 訄��訄�訄迡�.",
            hero_btn_research: "�迮���迮�郅?迡� ?茤��",
            hero_btn_contact: "�訄?郅訄郇��?,
            prof_img_alt: "��?�?�郋?�邽�訄 �邽?郇�? ?郋���迮��",
            section_about_badge: "?苺���衎",
            section_about_title: "�郕訄迡??�?�?迠郋??,
            about_history_title: "��?�??迠�?迮 ?訄?�訄郈",
            about_history_1_date: "�訄?��迣?�訄����?,
            about_history_1_desc: "�迮���迮��??�?�?�郋? �郋�迮??���訄??�訄��?訄��訄�?��?�?邽-?迮���迮??郇��?���?,
            about_history_2_date: "�迮�迮迠迮",
            about_history_2_desc: "���訄???茤?迮 �迡??迮�� 訇郋?�?�?�邽?郋?郋迣邽?迡郋?�?�?(Ph.D.), ?�迡訄???郇?赲?�邽�迮�� (���訄??",
            about_content_p1: "?�迡訄???郇?赲?�邽�迮��?迡?���訄???茤?迮 �迡??迮�� 訇郋?�?�?迡郋?�?�?�?迡��迮迠迮 訄郅�訄?郇訄郇 ?迮?�??���訄???郅訄��邽?訄?�??�?郱訄�? �迡???��??迠�?迮 �郋�迮??���訄??�訄?�����?訄?� �迡??迮�� �訄?訄��?迡??迮���迮�郅? 迠玼�迣�郱�郈 迠訄���邾�郇. ?郋?迡訄邿-訄� ?郅訄��邽?訄?�??���?迡?迡� ?訄?訄?訄�邽 �玼��?迡��?迠�?迮 迠訄�訄?迡??郇�迮?郅?��?�郋?迡訄郇?訄���?� 迠訄??迣�?訄?邽�訄�郅�� ����?迡?迣迮 ��?�����?�?�訄?��訄?�??",
            about_quote: '"��?�??�� ?�?迮???迮??訇玼迣�?迡?迠訄?�訄邿��??迡邽訄郅?迣, 訄迡訄邾 ?迮??迡����迡?�玼��?�迣迮 訄�?訄?�訄郇 �迮�迮?迮."',
            section_research_badge: "���苠?�??,
            section_research_title: "�迮迣�?迣??迮���迮?訇訄����訄�?,
            research_1_title: "���訄???郅訄��邽?訄?�??�?郱訄�?,
            research_1_desc: "���訄???郅訄��邽?訄?�??�?郱訄��郇�? ��?郅�迡???迮???迡??郋迣邽�郅�� ?迮迣�?迡?�郇 �迮�迮? ?迮���迮?",
            research_2_title: "�郅訄��邽?訄?�?�迡???��??,
            research_2_desc: "�迡???�珣?迡�郅���訄�迡??郅訄��邽?訄?�?�迮?�?� ?迮??�訄�邽�邽 ?郋?�?�� 訄���?� �訄?迡訄�.",
            research_3_title: "?訄?�����?訄?� �迡??迮?,
            research_3_desc: "�郋�迮??迠�?迮 ���訄??�迡??迮�� 訄�訄��郇迡訄�� ?郱訄�?��??�迮��迡� ?迮���迮?",
            section_pub_badge: "����觓���衎���?,
            section_pub_title: "�郕訄迡??�?�?��?邾?",
            pub_tab_books: "���訄?�訄�",
            pub_tab_papers: "�訄�訄?訄?訄?,
            pub_book_1_title: "�𪂇𠲍氺�匾??郇?�郇�? �訄�邽�� 2 (��???郱?郇�郇? ?�???訄?�?迡迮?�??��",
            pub_book_1_info: "��迡訄��訄郇迡訄? �邽�訄 �鉊?, �邽�郇 ???迣 | 2011.",
            pub_paper_1_title: "�芿軚� ?郱�郇-�訄?�?�? '衩郇�迠?���訄?� �迮迣�??迠訄?訇訄��郇�?' ?郋迣郇?�?赲�� ?郇�迮�郈�迮�訄�邽��?�� �訄�訄?迡??郇�迮?郅?�郈? ?迮�郕�郇 迠訄�訄?��??�邾? 訇��迣??,
            pub_paper_1_info: "Journal of Chinese Prose, 18-�郋?? 2025.06.",
            pub_paper_2_title: "�芿??� 衩��郇?�? ���� ���訄�邾訄��郅��?���訄?� ?郋��?郕訄郅�� �迮?�?�����",
            pub_paper_2_info: "��?訄?邽�訄�郅�� ?郋?赲?迣迮?�?� ?迮���迮�郅?? 1-�郋?? 2024.12.",
            pub_paper_3_title: "�芿??� 衩��郇?�? '?迠�訄??�郱? �訄����訇�?迡訄�?���� ���訄�邾訄��郅��?���訄?� ����訄�??迮���迮��?,
            pub_paper_3_info: "���� ��?迣�?訄?邽�訄�郅�� ?迮���迮�郅?? 25-�郋?? ��3, 2024.12.",
            pub_paper_4_title: "��'�玼???���? 迠�?迮 '�玼??�訄?訄�訄?訄?, ?�??��?迮�� �訄?訄 ?邽�郅�郅訄��郇�? ��訄郇��? ���郇 ?�迡�? '�郋�郇 ��迡訄??�邽' ���訄�邾訄�??迮迣�?�?迡??,
            pub_paper_4_info: "Journal of Chinese Prose, 15-�郋?? 2023.12.",
            pub_paper_5_title: "�芿𤧸𦁤?𦁤� 訄郅??迮??迠訄?�迡� ?訄?郋?邽?訄�邽�郅訄� ���訄?� ?迮���迮? �訄??��?郇�? '?訄?��郇 �訄迡訄�郱?��?��訄?? 迠邽?訄��?迡訄�?'?���?邽' ?迮迣�?�?迡??,
            pub_paper_5_info: "Journal of Chinese Prose, 13-�郋?? 2022.12.",
            contact_title: "������衎苤",
            contact_desc: "�訄?郅訄郇�� ?��郇 �茤?迮?迡??訄�?訄�訄��?�郋?迡訄郇�?�郱.",
            contact_label_phone: "?迮?迮�郋??,
            contact_label_email: "衪郅?��?郇迡�??郋��?,
            contact_label_office: "��?�",
            contact_office_value: "�郋?郕赲訄?迣 ?郇?赲?�邽�迮��, �郋�迮?,
            contact_phone_value: "063-850-7120",
            form_placeholder_name: "��?迠茤?�",
            form_placeholder_email: "衪郅?��?郇迡�??郋��?,
            form_placeholder_message: "??訇訄�郅訄邾訄?�郱",
            form_submit: "��訇迮��",
            form_success: "??訇訄�郅訄邾?����?迠�訇迮��?迡?",
            form_error: "�訄�迮 ?��郇 訄郅迡�.",
            footer_copyright: "?2026 ��?�?�郋?�邽�訄 �邽?? �訄�郅�� �珣����訄� �郋��訄郅�訄??",
            wku_name_en: "WONKWANG UNIVERSITY",
            nav_mobile_toggle: "��?�?,
            back_to_top_title: "�郋�訄���訄"
        },
        th: {
            site_title: "?兒?鉊?�?␡?鉊�葡?␡?鉆?Mira Kim - ?﹤???葷??�鉊Ｒ葡?丞?鉊Ｒ葷?冢�鉊�葷?耜�",
            site_description: "?�?抉�鉊?�鉊?�鉆?葉?Ｒ�鉊?�?�?𥔿�?跃�鉊?�?�?鉊?�?冢�鉊?葡?芹�鉊?葡?�?鉊?腺?� Mira Kim ?兒?鉊?�?␡?鉊�葡?␡?鉆?葷??�鉊?腺?鉮??�葵?遤?鉊??鉊跃�?抉?鉊﹤葵?晤?鉊??鉊跃�?䓃�鉊�葡?徇?鉊??�????﹤???葷??�鉊Ｒ葡?丞?鉊Ｒ葷?冢�鉊�葷?耜�",
            wku_name: "?﹤???葷??�鉊Ｒ葡?丞?鉊Ｒ葷?冢�鉊�葷?耜�",
            header_title: "?兒?鉊?�?␡?鉊�葡?␡?鉆?葷??�鉊?腺 ?芹�鉊?�?晤�鉊�葷?耜腹?芹?鉊﹤�?晤�鉊?�?�?�?鉊徇艇?�-?�???,
            nav_profile: "?��鉊???嫩?鉊?�?抉�鉊𨫼?鉊?,
            nav_research: "?�?鉊?葷??�鉊?腺",
            nav_publications: "?厢?鉊�葡?跃?鉊??耜�?耜腦",
            nav_contact: "?𨫼葩?𠰍�?�??,
            hero_sub_title: "?�?鉊?腹?𥔿腦?啤?鉊?�?␡?鉊徇葷?�?鉊��?嫩?鉊??晤�鉊温葡?�?鉊?葷??�鉊?�?耜腦",
            prof_name: "Mira Kim",
            prof_title_suffix: "?兒?鉊?�?␡?鉊�葡?␡?鉆?,
            hero_desc: "?抉?鉊�萵?Ｒ?鉊?腦?㮙�鉊?腦?﹤�鉊?�?�?鉊?葵?芹?鉊��?菽�鉊﹤葦?耜葷??�鉊Ｒ葡?丞?鉊Ｒ葷?冢�鉊�葷?耜� ?鉮?鉊徇�?凼?鉊???��鉊𥔿�鉊跃葵?啤�鉊?�?�?𢺋虞?�?鉊﹤�?耜�?抉?鉊𢺋?鉊�葡?␡???葦?抉�鉊?�?𥔿腦?啤�鉊?�鉊?�?丞?鉊﹤虜?﹤?鉊???芹?鉊?腺?�??﹤�",
            hero_btn_research: "?𠰍號?�?鉊跃葷??�鉊?腺",
            hero_btn_contact: "?𨫼葩?𠰍�?�??,
            prof_img_alt: "?␡?鉊𥔿�鉊𥔿??��?丞�鉊?葡?芹�鉊?葡?�?鉊?腺?� Mira Kim",
            section_about_badge: "?�?�??�腺?抉�鉊?�",
            section_about_title: "?�?芹�鉊跃�?耜�?抉?鉊𢺋?鉊�葡?�",
            about_history_title: "?�?鉊?落?嗣�鉊?葡?�?鉊?�?␡?鉊?�?�?鉊?�?�",
            about_history_1_date: "?𥔿萵?��鉊??晤?,
            about_history_1_desc: "?兒?鉊?�?␡?鉊�葡?␡?鉆?葷??�鉊?腺 ?芹�鉊?�?晤�鉊�葷?耜腹?芹?鉊﹤�?晤�鉊?�?�?�?鉊徇艇?�-?�????﹤???葷??�鉊Ｒ葡?丞?鉊Ｒ葷?冢�鉊�葷?耜�",
            about_history_2_date: "?抉?鉊?葩?�?鉊?落?嗣�鉊?葡",
            about_history_2_desc: "?𥔿腦??�鉊温葡?�?冢�鉊?葡?�?鉊?腦?␡�鉊�腦?␡?鉊�葭?跃�鉊????� ?﹤???葷??�鉊Ｒ葡?丞?鉊Ｒ�?嫩�鉊?� (?�???",
            about_content_p1: "?徇?鉊?�?�?鉊�葵?喪�鉊?�?��鉊?腦?兒?鉊�萱?耜腦?啤�鉊?�?𥔿腦??�鉊温葡?�?冢�鉊?葡?�?鉊?腦?␡�鉊�腦?␡?鉊�葭?跃�鉊????�?�?鉊�腹?徇?鉊?葩?鉮?鉊?艇?晤?鉊颴號?𠰍萵?� ?凼?鉊跃�?𠰍�?鉮?鉊�葡?␡?鉊??晤?鉆�鉊𢺋?鉊�艇?嗣�鉆��?𠰍�?耜�?␡�鉊???��鉆?葷?�??跃�?丞?鉊?葵????�?鉊?葷??�鉊?腦?㮙�鉊?腦?␡�鉊�腦?␡???�?鉊?葷?␡??㮙�?␡??﹤�?𥔿腦?菽?鉊?�鉊???Ｒ�鉆�鉊�葡?徇?鉊??�????跃?鉊��?耜�?跃???�?晤�鉊Ｒ萵?��鉊徇�?�?鉊?腹?芹�鉆��?��鉊�葡?␡�鉊?�?抉?鉊﹤葵?﹤?鉊Ｒ�?徇?鉆��?冢�鉊𨫼?鉊?葡?�?鉊?葵?芹?鉊��?丞?鉆��?抉�鉊?�?﹤�鉊??Ｒ?鉊?葵?𨫼腦?䓃�鉊徇腹?�??��鉊Ｒ�?𢺋� AI",
            about_quote: '"?抉?鉊𢺋?鉊�葡?␡�鉊?葉?�?鉊?葵?跃�鉊跃葡?鉮??��?𢺋虞?�?鉊﹤�?Ｒ�鉊???菽�鉆�艇?啤�鉊?�?�?鉊??鉊??�?𥔿�?跃??跃�?耜�?�?鉊�葵?嫩�鉊�葷?耜腹?�?��鉊?�?��鉊嫩�?��鉆�艇?啤?鉊??芹?鉊?腺"',
            section_research_badge: "?�?鉊?葷??�鉊?腺",
            section_research_title: "?芹?鉊�葡?抉?鉊�萵?Ｒ??丞萵?�",
            research_1_title: "?␡�鉊???��鉆?葷?�??跃�?丞?鉊?葵???,
            research_1_desc: "?�?鉊?落?嗣�鉊?葡?�?𢺋葩?�?鉊?�?�?�??�腺?抉�鉊?�?␡?鉊𥔿�鉊?�鉆�艇?啤�鉊嫩腹????丞萵?��鉊?�?�?鉊?腹?�?鉊?�鉊???␡�鉊???��鉆?葷?�??跃�?丞?鉊?葵???,
            research_2_title: "?�?鉊?葷??�鉊?腦?㮙�鉊?腦?␡�鉊�腦?␡?鉊�艇?耜葵?芹?鉊?,
            research_2_desc: "?�?鉊?葷??�鉊�腦?耜萼?徇�鉊�虜?㮙�鉆�葡?鉮?鉊�葷?␡??㮙�?␡??﹤�?�?鉊跃�?戈?鉊?葭?�?鉊?葵?芹?鉊��?丞?鉊?????鉮�鉊?�?𥔿腦?啤?鉊?�???鉊?葵?𨫼腦?�",
            research_3_title: "?抉???�?�???腹?�?𥔿腦?菽?鉊?�鉊???Ｒ?,
            research_3_desc: "?�?鉊?�?␡?鉊�葵?冢�鉊�葷?耜腹?芹?鉊﹤�?晤�鉊?�?�?鉊?�?耜腦?�?鉊��?𥔿艇?菽�鉊Ｒ�?␡?鉊徇葷?�?鉊�葷?␡??㮙�?␡??﹤�?�?鉊徇艇?菽�鉊丞萼?�???,
            section_pub_badge: "?厢?鉊�葡?�",
            section_pub_title: "?�?鉊��?␡??﹤�?耜�?抉?鉊𢺋?鉊�葡?�",
            pub_tab_books: "?徇�鉊?�?芹?鉊?,
            pub_tab_papers: "???�?鉊?腹?抉?鉊�萵?�",
            pub_book_1_title: "�脚�鉊?萼?抉?鉊𨫼?鉊?葡?芹�鉊?�?兒?鉊丞�?啤�鉊?� 2 (?�?鉊�葵?﹤?鉊Ｒ�?抉�鉊??�?鉆?� ?遤?鉊??芹?鉊??遤?鉊?��",
            pub_book_1_info: "?��鉊丞腦?�?鉊﹤�?𠰍腺 Mira Kim, Kiyong Hong | 2011",
            pub_paper_1_title: "�䓃�鉊?腦?𨫼葭?�?鉊?腹?�?𢺋葩?��鉊??熈?鉊𥔿?鉊温�?耜�?冢?'???跃�鉊?�?鉮?鉆?�?��鉊?�鉊徇�?�??Ｒ�?��鉊? ?�?鉊??徇?鉊? ?��鉊徇腺?抉?�� ?𠒎腦?凼?鉊﹤�?抉?鉊﹤�?Ｒ?鉊Ｒ葡?﹤�鉊跃�?耜腦?�?𢺋虞?�?鉊﹤�?Ｒ�鉊�萵???耜腦?芹???葡?��鉊?�?��鉊?AI��",
            pub_paper_1_info: "?抉?鉊?葵?耜腦?␡�鉊???��鉆?葷?�??? ?凼�鉊?�?鉮???18, 2025.06",
            pub_paper_2_title: "�䓃�鉊?萱?脚??�葷?菽�鉊??跃�鉆?葷?�?鉊?�鉊?腺?�?鉊?葵?␡�鉊?�?芹???�?䓃?鉊嫩�?颴?鉆?(Lufu) ?�?鉊�葦?抉?鉊�葉?抉??��?𢺋葩?� [Wang Yucheng]��",
            pub_paper_2_info: "?�?鉊?葷??�鉊?腺?𠒎虜?鉮�鉊??晤�鉊温葡?鉮?鉊�腹?跃?鉊?腺?兒?鉊?�?␡? ?凼�鉊?�?鉮???1, 2024.12",
            pub_paper_3_title: "�䓃�鉊?腦?兒?鉊�萱?耜�???凼?鉊��?凼�鉆�鉊�葭?�?鉊?�?晤�鉊�葡?␡?鉊?�?耜�?芹???�?䓃?鉊嫩�?颴?鉆��?耜腹?徇?鉊?�?凼??'?�?鉊��?獅�鉊? ?�?鉊�葦?抉?鉊�葉?抉??��?𢺋葩?���",
            pub_paper_3_info: "?�?鉊?葷??�鉊?腺?﹤�鉊??Ｒ?鉊?葵?𨫼腦?䓃�鉊??抉?鉊温�?耜�?�?𥔿葩?�, ?凼�鉊?�?鉮???25, ?�?丞�鉊﹤�?菽?3, 2024.12",
            pub_paper_4_title: "��'?�?鉊?�?丞?鉊��?冢�鉆�腹?�' ?�?鉊?'?�?鉊?�?﹤�鉊???�?鉆? ?�?鉊?腹?芹?鉊��?丞�鉊�� ?�?鉊��?晤�鉊温葡?𢺋�?��鉆�鉊﹤虞?冢�鉊?腹?晤?鉊?葡?𢺋葷?�?鉆?�?�? ?兒?鉊�萱?耜�?␡�鉊?'?丞?鉆�葷?徇?鉊?�?徇?鉊嫩�?𨫼葡?跃�鉊?�' ?�?鉊��?冢?鉊徇腺?耜�???鉊?�?,
            pub_paper_4_info: "?抉?鉊?葵?耜腦?␡�鉊???��鉆?葷?�??? ?凼�鉊?�?鉮???15, 2023.12",
            pub_paper_5_title: "�䓃�鉊?腦?𠒎葩?�?鉊?�?耜�?耜腦?鉮?鉆�葦?凼�鉊𥔿�鉊跃�???冢?鉆�葡?��鉊???�?鉊?�?␡??Ｒ�?␡?鉆?�?丞?鉊�葡?␡�鉊?�?鉮?鉊? ?兒?鉊�萱?耜�?␡�鉊?'?�?芹?鉊?腺?�??? ?�?'?遤?鉊��?��鉊𥔿?鉊𨫼�鉊?�?�??Ｒ�?徇?鉊??�?𢺋葡' ?�?鉊��?徇?鉊?�?詮��?,
            pub_paper_5_info: "?抉?鉊?葵?耜腦?␡�鉊???��鉆?葷?�??? ?凼�鉊?�?鉮???13, 2022.12",
            contact_title: "?𨫼葩?𠰍�?�??,
            contact_desc: "?�????耜�??�鉊𨫼�鉊???�?鉊跃�?凼?鉊﹤號?丞�鉆?葡?跃?鉆�葡?��鉊?�",
            contact_label_phone: "?��鉊?落?晤�鉊??",
            contact_label_email: "?冢??�鉊﹤艇",
            contact_label_office: "?徇�鉊???鉮?鉊�葡?�",
            contact_office_value: "?﹤???葷??�鉊Ｒ葡?丞?鉊Ｒ葷?冢�鉊�葷?耜� ?�?�?鉊徇艇?菽�鉊𨫼?,
            contact_phone_value: "063-850-7120",
            form_placeholder_name: "?𢺋虞?�???跃?鉊﹤葵?�?鉊?,
            form_placeholder_email: "?冢??�鉊﹤艇",
            form_placeholder_message: "?��鉊???抉?鉊?,
            form_submit: "?芹�鉊?,
            form_success: "?芹�鉊��?凼?鉊�葷?耜腹?芹?鉆�鉊?�?�",
            form_error: "?�?�?鉊?�鉆?葉?厢?鉊?�鉊丞葡?�",
            footer_copyright: "?2026 ?兒?鉊?�?␡?鉊�葡?␡?鉆?Mira Kim. ?芹�鉊?�?丞?鉊�葵??�鉊?葩?�",
            wku_name_en: "WONKWANG UNIVERSITY",
            nav_mobile_toggle: "?�?﹤�鉊?,
            back_to_top_title: "?�?鉊?�?��鉊?�鉊?�??"
        }
    };

            const currentLangText = document.querySelector('.current-lang');
    const langOptions = document.querySelectorAll('.lang-dropdown li');

    // Performance Optimization: Cache all elements that need translation once
    const cachedElements = {
        i18n: document.querySelectorAll('[data-i18n]'),
        alt: document.querySelectorAll('[data-i18n-alt]'),
        placeholder: document.querySelectorAll('[data-i18n-placeholder]'),
        aria: document.querySelectorAll('[data-i18n-aria-label]'),
        title: document.querySelectorAll('[data-i18n-title]')
    };

    const updateLanguage = (lang) => {
        const t = translations[lang];
        if (!t) return;

        // Update elements with data-i18n using cached list
        cachedElements.i18n.forEach(el => {
            const key = el.getAttribute('data-i18n');
            if (t[key]) el.innerText = t[key];
        });

        // Update alt text
        cachedElements.alt.forEach(el => {
            const key = el.getAttribute('data-i18n-alt');
            if (t[key]) el.setAttribute('alt', t[key]);
        });

        // Update placeholders
        cachedElements.placeholder.forEach(el => {
            const key = el.getAttribute('data-i18n-placeholder');
            if (t[key]) el.setAttribute('placeholder', t[key]);
        });

        // Update aria-labels
        cachedElements.aria.forEach(el => {
            const key = el.getAttribute('data-i18n-aria-label');
            if (t[key]) el.setAttribute('aria-label', t[key]);
        });

        // Update titles
        cachedElements.title.forEach(el => {
            const key = el.getAttribute('data-i18n-title');
            if (t[key]) el.setAttribute('title', t[key]);
        });

        // Update document title and meta description for SEO
        if (t.site_title) document.title = t.site_title;
        if (t.site_description) {
            const metaDesc = document.querySelector('meta[name="description"]');
            if (metaDesc) metaDesc.setAttribute('content', t.site_description);
        }

        const langNames = { 
            ko: "한국어", 
            en: "English", 
            zh: "中文", 
            ja: "日本語", 
            de: "Deutsch", 
            es: "Español",
            ne: "नेपाली",
            mn: "Монгол",
            vi: "Tiếng Việt",
            bn: "বাংলা",
            az: "Azərbaycan",
            uz: "O'zbek",
            id: "Bahasa Indonesia",
            zh_hant: "繁體中文",
            kk: "Қазақша",
            th: "ไทย"
        };
        
        if (currentLangText) {
            currentLangText.innerText = langNames[lang] || lang;
        }
        localStorage.setItem('preferredLang', lang);
    };

    langOptions.forEach(option => {
        option.addEventListener('click', () => {
            const lang = option.getAttribute('data-lang');
            updateLanguage(lang);
        });
    });

    // Mobile Navigation Logic
    const mobileToggle = document.querySelector('.mobile-nav-toggle');
    const navMenu = document.getElementById('nav-menu');
    const navLinks = document.querySelectorAll('#main-nav a');

    if (mobileToggle && navMenu) {
        mobileToggle.addEventListener('click', () => {
            mobileToggle.classList.toggle('active');
            navMenu.classList.toggle('active');
        });

        navLinks.forEach(link => {
            link.addEventListener('click', () => {
                mobileToggle.classList.remove('active');
                navMenu.classList.remove('active');
            });
        });
    }

    // Initial language setup
    const savedLang = localStorage.getItem('preferredLang') || 'ko';
    updateLanguage(savedLang);

    // Tab switching logic
    const tabBtns = document.querySelectorAll('.tab-btn');
    const booksList = document.getElementById('books-list');
    const papersList = document.getElementById('papers-list');

    tabBtns.forEach(btn => {
        btn.addEventListener('click', () => {
            tabBtns.forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
            const tabName = btn.getAttribute('data-tab');
            if (tabName === 'books') {
                booksList.style.display = 'grid';
                papersList.style.display = 'none';
            } else {
                booksList.style.display = 'none';
                papersList.style.display = 'grid';
            }
        });
    });

    // Scroll reveal
    const revealElements = document.querySelectorAll('.section, .hero-text, .hero-image, .research-item, .about-card');
    const revealCallback = (entries, observer) => {
        entries.forEach(entry => {
            if (entry.isIntersecting) {
                entry.target.classList.add('revealed');
                observer.unobserve(entry.target);
            }
        });
    };
    const revealObserver = new IntersectionObserver(revealCallback, { threshold: 0.15 });
    revealElements.forEach(el => {
        el.style.opacity = '0';
        el.style.transform = 'translateY(30px)';
        el.style.transition = 'all 0.8s cubic-bezier(0.165, 0.84, 0.44, 1)';
        revealObserver.observe(el);
    });

    const style = document.createElement('style');
    style.innerHTML = ".revealed { opacity: 1 !important; transform: translateY(0) !important; }";
    document.head.appendChild(style);

    // Back to top
    const backToTopBtn = document.getElementById('back-to-top');
    window.addEventListener('scroll', () => {
        if (window.scrollY > 400) backToTopBtn.classList.add('visible');
        else backToTopBtn.classList.remove('visible');
    });
    if (backToTopBtn) {
        backToTopBtn.addEventListener('click', () => {
            window.scrollTo({ top: 0, behavior: 'smooth' });
        });
    }
});

