import json
import os

file_path = r'd:/Antigravity/wku_prof_site/scratch/all_translations.json'

with open(file_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

# Batch 1: zh, ja, zh_hant
data['zh'] = {
    "site_title": "金美罗教授 - 圆光大学 韩中关系研究院",
    "site_description": "圆光大学韩中关系研究院研究教授金美罗教授的官方网站。提供中国古典散文、文学批评、韩中比较文学研究及主要著作信息。",
    "wku_name": "圆光大学",
    "header_title": "韩中关系研究院 研究教授",
    "nav_profile": "个人简介",
    "nav_research": "研究领域",
    "nav_publications": "学术成果",
    "nav_contact": "联系方式",
    "hero_sub_title": "学术与智慧的和谐",
    "prof_name": "金美罗",
    "prof_title_suffix": "教授",
    "hero_desc": "在圆光大学韩中关系研究院研究中国古典散文，致力于连接传统深度与现代视角的学术桥梁。",
    "hero_btn_research": "浏览研究",
    "hero_btn_contact": "联系我",
    "prof_img_alt": "金美罗教授个人照片",
    "section_about_badge": "关于",
    "section_about_title": "学术历程",
    "about_history_title": "学历与经历",
    "about_history_1_date": "现在",
    "about_history_1_desc": "圆光大学 韩中关系研究院 研究教授",
    "about_history_2_date": "最高学位",
    "about_history_2_desc": "中国 复旦大学 文学博士 (中国古代文学专业)",
    "about_content_p1": "在复旦大学获得中国古代文学博士学位后，一直从事中国古典散文、文学批评以及韩中比较文学领域的深入研究。特别关注古典文本的现代诠释以及利用AI的新人文主义研究方法。",
    "about_quote": "\"学术是连接过去与现在的对话，是理解人类与时代的窗户。\"",
    "section_research_badge": "研究",
    "section_research_title": "主要研究领域",
    "research_1_title": "中国古典散文",
    "research_1_desc": "深入研究以唐宋八大家为代表的中国古典散文的文体及思想背景。",
    "research_2_title": "中国古典文学批评",
    "research_2_desc": "通过古典文学理论和批评史脉络分析并重新审视文学价值。",
    "research_3_title": "韩中比较文学",
    "research_3_desc": "从比较文学视角考察韩中两国文学间的相互影响与交流状态。",
    "section_pub_badge": "学术成果",
    "section_pub_title": "学术及著述活动",
    "pub_tab_books": "著作",
    "pub_tab_papers": "学术论文",
    "pub_book_1_title": "《中国美术史2 (从魏晋到隋唐)》",
    "pub_book_1_info": "金美罗、洪基镛合译 | Dareun Saenggak | 2011.",
    "pub_paper_1_title": "《柳宗元〈永州八记〉的认知解释初探——兼论与AI图像生成的结合尝试》",
    "pub_paper_1_info": "《中国散文研究集刊》第18辑, 2025.06.",
    "pub_paper_2_title": "《王禹偁的律赋创作时论》",
    "pub_paper_2_info": "《韩国人文融合研究》第1辑, 2024.12.",
    "pub_paper_3_title": "《王禹偁〈庄子〉题材律赋创作小考》",
    "pub_paper_3_info": "《开明精神人文研究》25辑第3号, 2024.12.",
    "pub_paper_4_title": "《“养花”与“赏花”，宋代都市文人的小确幸：以欧阳修〈洛阳牡丹记〉为中心》",
    "pub_paper_4_info": "《中国散文研究集刊》第15辑, 2023.12.",
    "pub_paper_5_title": "《关于学习与记录的范式化考查：以茅坤〈唐宋八大家文钞〉收录的“学记”为中心》",
    "pub_paper_5_info": "《中国散文研究集刊》第13辑, 2022.12.",
    "contact_title": "联系我们",
    "contact_desc": "讲演邀请、学术交流及其他咨询，请通过以下方式联系。",
    "contact_label_phone": "联系电话",
    "contact_label_email": "电子邮箱",
    "contact_label_office": "研究室",
    "contact_office_value": "全罗北道益山市益山大路460 圆光大学 学军团3楼 韩中关系研究院",
    "contact_phone_value": "+82-63-850-7120",
    "form_placeholder_name": "姓名",
    "form_placeholder_email": "电子邮箱",
    "form_placeholder_message": "请输入咨询内容",
    "form_submit": "发送",
    "form_success": "消息已成功发送。",
    "form_error": "发生错误，请稍后再试。",
    "footer_copyright": "© 2026 金美罗教授. 保留所有权利。",
    "wku_name_en": "WONKWANG UNIVERSITY",
    "nav_mobile_toggle": "切换菜单",
    "back_to_top_title": "回到顶部"
}

data['ja'] = {
    "site_title": "金美羅 教授 - 円光大学 韓中関係研究院",
    "site_description": "円光大学韓中関係研究院の研究教授、金美羅教授の公式ホームページです。中国古典散文、文学批評、韓中比較文学の研究および主要著書の情報を提供します。",
    "wku_name": "円光大学",
    "header_title": "韓中関係研究院 研究教授",
    "nav_profile": "プロフィール",
    "nav_research": "研究分野",
    "nav_publications": "学術成果",
    "nav_contact": "連絡先",
    "hero_sub_title": "学問と知恵の調和",
    "prof_name": "金美羅",
    "prof_title_suffix": "教授",
    "hero_desc": "円光大学韓中関係研究院で中国古典散文を研究し、伝統の深みと現代的視点をつなぐ学術的架け橋の役割を担っています。",
    "hero_btn_research": "研究を見る",
    "hero_btn_contact": "お問い合わせ",
    "prof_img_alt": "金美羅教授のプロフィール写真",
    "section_about_badge": "ABOUT",
    "section_about_title": "学問の軌跡",
    "about_history_title": "学歴・経歴",
    "about_history_1_date": "現在",
    "about_history_1_desc": "円光大学 韓中関係研究院 研究教授",
    "about_history_2_date": "最終学位",
    "about_history_2_desc": "中国 復旦大学 文学博士 (中国古代文学専攻)",
    "about_content_p1": "復旦大学で中国古代文学の博士号を取得後、中国古典散文、文学批評、および韓中比較文学の分野で深い研究を行ってきました。特に古典テキストの現代的解釈や、AIを活用した新しい人文学的アプローチにも関心を持っています。",
    "about_quote": "\"学問は過去と現在をつなぐ対話であり、人と時代を理解する窓です。\"",
    "section_research_badge": "RESEARCH",
    "section_research_title": "主な研究分野",
    "research_1_title": "中国古典散文",
    "research_1_desc": "唐宋八大家をはじめとする中国古典散文の文体と思想的背景を深く研究しています。",
    "research_2_title": "中国古典文学批評",
    "research_2_desc": "古典文学理論と批評史的文脈を通じて文学的価値を分析し、再評価します。",
    "research_3_title": "韓中比較文学",
    "research_3_desc": "韓国と中国の文学間の相互影響と交流様式を比較文学的観点から考察します。",
    "section_pub_badge": "PUBLICATIONS",
    "section_pub_title": "学術・著述活動",
    "pub_tab_books": "著書",
    "pub_tab_papers": "学術論文",
    "pub_book_1_title": "『中国美術史2 (魏晋から隋唐まで)』",
    "pub_book_1_info": "金美羅、洪基鏞 共訳 | 他の思考 | 2011.",
    "pub_paper_1_title": "「柳宗元の『永州八記』の認知的解釈初探—AI画像生成との連携の試みを兼ねて」",
    "pub_paper_1_info": "『中国散文研究集刊』第18輯, 2025.06.",
    "pub_paper_2_title": "「王禹偁の律賦創作時論」",
    "pub_paper_2_info": "『韓国人文融合研究』第1輯, 2024.12.",
    "pub_paper_3_title": "「王禹偁の『荘子』題材律賦創作小考」",
    "pub_paper_3_info": "『開かれた精神人文学研究』25集第3号, 2024.12.",
    "pub_paper_4_title": "「『養花』と『賞花』、宋代都市文人の小確幸：欧陽修の≪洛陽牡丹記≫を中心に」",
    "pub_paper_4_info": "『中国散文研究集刊』第15輯, 2023.12.",
    "pub_paper_5_title": "「学びと記録の典範化に関する考察：茅坤の≪唐宋八大家文抄≫収録『学記』を中心に」",
    "pub_paper_5_info": "『中国散文研究集刊』第13輯, 2022.12.",
    "contact_title": "CONTACT",
    "contact_desc": "講演依頼、学術交流、その他のお問い合わせは以下の連絡先までお願いいたします。",
    "contact_label_phone": "電話番号",
    "contact_label_email": "メール",
    "contact_label_office": "研究室",
    "contact_office_value": "全羅北道益山市益山大路460 円光大学 学軍団3階 韓中関係研究院",
    "contact_phone_value": "+82-63-850-7120",
    "form_placeholder_name": "お名前",
    "form_placeholder_email": "メールアドレス",
    "form_placeholder_message": "お問い合わせ内容を入力してください",
    "form_submit": "送信",
    "form_success": "メッセージが送信されました。",
    "form_error": "エラーが発生しました。しばらくしてからもう一度お試しください。",
    "footer_copyright": "© 2026 金美羅 教授. All rights reserved.",
    "wku_name_en": "WONKWANG UNIVERSITY",
    "nav_mobile_toggle": "メニュー切替",
    "back_to_top_title": "トップへ戻る"
}

data['zh_hant'] = {
    "site_title": "金美羅教授 - 圓光大學 韓中關係研究院",
    "site_description": "圓光大學韓中關係研究院研究教授金美羅教授的官方網站。提供中國古典散文、文學批評、韓中比較文學研究及主要著作信息。",
    "wku_name": "圓光大學",
    "header_title": "韓中關係研究院 研究教授",
    "nav_profile": "個人簡介",
    "nav_research": "研究領域",
    "nav_publications": "學術成果",
    "nav_contact": "聯繫方式",
    "hero_sub_title": "學術與智慧的和諧",
    "prof_name": "金美羅",
    "prof_title_suffix": "教授",
    "hero_desc": "在圓光大學韓中關係研究院研究中國古典散文，致力於連接傳統深度與現代視角的學術橋樑。",
    "hero_btn_research": "瀏覽研究",
    "hero_btn_contact": "聯繫我",
    "prof_img_alt": "金美羅教授個人照片",
    "section_about_badge": "關於",
    "section_about_title": "學術歷程",
    "about_history_title": "學歷與經歷",
    "about_history_1_date": "現在",
    "about_history_1_desc": "圓光大學 韓中關係研究院 研究教授",
    "about_history_2_date": "最高學位",
    "about_history_2_desc": "中國 復旦大學 文學博士 (中國古代文學專業)",
    "about_content_p1": "在復旦大學獲得中國古代文學博士學位後，一直從事中國古典散文、文學批評以及韓中比較文學領域的深入研究。特別關注古典文本的現代詮釋以及利用AI的新人文主義研究方法。",
    "about_quote": "\"學術是連接過去與現在的對話，是理解人類與時代的窗戶。\"",
    "section_research_badge": "研究",
    "section_research_title": "主要研究領域",
    "research_1_title": "中國古典散文",
    "research_1_desc": "深入研究以唐宋八大家為代表的中國古典散文的文體及思想背景。",
    "research_2_title": "中國古典文學批評",
    "research_2_desc": "通過古典文學理論和批評史脈絡分析並重新審視文學價值。",
    "research_3_title": "韓中比較文學",
    "research_3_desc": "從比較文學視角考察韓中兩國文學間的相互影響與交流狀態。",
    "section_pub_badge": "學術成果",
    "section_pub_title": "學術及著述活動",
    "pub_tab_books": "著作",
    "pub_tab_papers": "學術論文",
    "pub_book_1_title": "《中國美術史2 (從魏晉到隋唐)》",
    "pub_book_1_info": "金美羅、洪基鏞合譯 | Dareun Saenggak | 2011.",
    "pub_paper_1_title": "《柳宗元〈永州八記〉的認知解釋初探——兼論與AI圖像生成的結合嘗試》",
    "pub_paper_1_info": "《中國散文研究集刊》第18輯, 2025.06.",
    "pub_paper_2_title": "《王禹偁的律賦創作時論》",
    "pub_paper_2_info": "《韓國人文融合研究》第1輯, 2024.12.",
    "pub_paper_3_title": "《王禹偁〈莊子〉題材律賦創作小考》",
    "pub_paper_3_info": "《開明精神人文研究》25輯第3號, 2024.12.",
    "pub_paper_4_title": "《“養花”與“賞花”，宋代都市文人的小確幸：以歐陽修〈洛陽牡丹記〉為中心》",
    "pub_paper_4_info": "《中國散文研究集刊》第15輯, 2023.12.",
    "pub_paper_5_title": "《關於學習與記錄的範式化考查：以茅坤〈唐宋八大家文鈔〉收錄的“學記”為中心》",
    "pub_paper_5_info": "《中國散文研究集刊》第13輯, 2022.12.",
    "contact_title": "聯繫我們",
    "contact_desc": "講演邀請、學術交流及其他諮詢，請通過以下方式聯繫。",
    "contact_label_phone": "聯繫電話",
    "contact_label_email": "電子郵箱",
    "contact_label_office": "研究室",
    "contact_office_value": "全羅北道益山市益山大路460 圓光大學 學軍團3樓 韓中關係研究院",
    "contact_phone_value": "+82-63-850-7120",
    "form_placeholder_name": "姓名",
    "form_placeholder_email": "電子郵箱",
    "form_placeholder_message": "請輸入諮詢內容",
    "form_submit": "發送",
    "form_success": "消息已成功發送。",
    "form_error": "發生錯誤，請稍後再試。",
    "footer_copyright": "© 2026 金美羅教授. 保留所有權利。",
    "wku_name_en": "WONKWANG UNIVERSITY",
    "nav_mobile_toggle": "切換菜單",
    "back_to_top_title": "回到頂部"
}

with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Batch 1 complete.")
